### ISSUE TITLE
thinkjs 2.0需求收集

### ISSUE THREAD

**Issue by welefen** [75team/thinkjs#146]
今年会开发thinkjs 2.0版本，这里收集大家需求，欢迎提各种意见。

**Comment by richenlin** [comment]
1、mongodb的完整支持。mongo即能兼容关系数据库的基本结构，又具有Nosql的特性，实在是关系数据库转型的神器。在需求变更频繁的场景，太爱mongo的动态表结构了
2、之前跟群主聊过 thinkphp 3.2的特性，独立分组和智能加载的特性

**Comment by xuexb** [comment]
类似`layouts`&`block`的功能是框架的还是模板引擎的？现在一直`include`感觉不是很好

**Comment by rekey** [comment]
@xuexb 这个是模板引擎支持的。跟框架是无关的。

**Comment by welefen** [comment]
@xuexb 可以使用swig模版引擎，这个是支持继承的

**Comment by welefen** [comment]
@rekey 你还经常来帮回答问题，不错啊

**Comment by qgy18** [comment]
@rekey @welefen 赞~

会出个脚手架么？自动生成后台管理什么的。

**Comment by welefen** [comment]
http://naotu.baidu.com/viewshare.html?shareId=asqobqvcjrk8  2.0设计草案见这里

**Comment by xuexb** [comment]
@welefen @rekey ok 3q

**Comment by udbmnm** [comment]
希望用上es6新特性，generator等，单字母函数改名，看了草案很期待，想加的作者都想到了

**Comment by AlphaTr** [comment]
希望支持单 module，url 反解析

**Comment by ckken** [comment]
希望剥离view层的模型 深化restful的结构 以后开发将走mean结构 而且nodejs 对静态处理并不是强项 可以完全用nginx加载

**Comment by ckken** [comment]
对于 thinkjs 以及 express restify 的一些AB测试 http://js.wvovo.com/topic/10/%E5%AF%B9%E4%BA%8E%E7%9B%AE%E5%89%8Dnodejs%E6%A1%86%E6%9E%B6%E7%9A%84%E4%B8%80%E4%BA%9B%E5%AF%B9%E6%AF%94-%E5%B9%B6%E5%8F%91%E5%A4%84%E7%90%86

**Comment by rekey** [comment]
鉴于  io.js 和 node.js 的情况，应该慎重考虑下在发布里说明下在哪些平台版本下测试通过以及可能的话有的推荐平台了。。。

P.s : 对 io.js 最后回归 node.js 表示悲观。目前在推动主力使用 io.js

**Comment by ckken** [comment]
@rekey ??什么意思 回归了？

**Comment by rekey** [comment]
@ckken 没啊，iojs表示最后代码想回归 nodejs，我表示下悲观而已。看完整我说的嘛。

**Comment by welefen** [comment]
@ckken express restify 框架做的功能很少，主要都是通过插件来完成的
thinkjs默认就会做数据解析，路由识别等很多常用的功能，所以性能上肯定要差一些。如果express里调用插件做到这些功能，性能应该是差不多的。

**Comment by ckken** [comment]
@welefen nodejs 体现在高兵法 和性能上面  至于功能性问题 我觉得 strongloop 也是可参考的点 对于全栈模型 感觉 已经不符合时代发展 我之前 也写了个 koa 的blog 框架 瓶颈在于静态加载 前端的东西 还是给 nginx 比较靠谱

**Comment by welefen** [comment]
@ckken thinkjs也没做静态资源的加载啊，里面的静态资源处理是便于开发环境下的。线上推荐用nginx来处理。

至于功能性方面，thinkjs的目标是让开发更快，不用自己去搭建很多东西。如果只是个很简单的框架，直接用express之类的就可以了。

**Comment by ckken** [comment]
建议看看sailsjs  高效 简单 傻子都会做crud了 妈妈再也不怕你们不会编程了 有新规划麻烦通知下 一个人写框架好无聊 建议用es6 特性来做

**Comment by richenlin** [comment]
建议 Dispatcher类增加一个URL大小写自动转换的功能：
例如  Admin/Public/Login   和 admin/public/login  同等
admin/public_logout  等价  Admin/PublicLogout   
其中 Group和Controller为大驼峰命名，action为小驼峰命名
更加符合用户输入URL习惯，也有利于SEO
附上驼峰转换的函数：

/**
 * 小驼峰命名正则转换
 * @type {RegExp}
 */
var sCamelReg = function(str){
    var re = /_(\w)/g;
    return str.replace(re, function(all,letter){
        return letter.toUpperCase();
    });
};
/**
 * 大驼峰命名正则转换
 * @type {RegExp}
 */
var bCamelReg = function(str){
    var re = /_(\w)/g;
    var rstr =  str.slice(1).replace(re, function(all,letter){
        return letter.toUpperCase();
    });
    return str[0].toUpperCase() + rstr;
};

**Comment by denvey** [comment]
增加对redis和ssdb的支持哦，这些都还是能用到的，听说360不是很多项目都在用ssdb

**Comment by zwhjs** [comment]
建议添加随机图片验证码的功能

**Comment by yuu2lee4** [comment]
现在php下最流行的应该是laravel吧  可以模仿模仿 取其精华去其糟粕

**Comment by Wizzercn** [comment]
建议集成类似Apache Shiro 权限框架功能
