### ISSUE TITLE
部署到腾讯云服务器创建目录和文件时，不在www目录下，而是创建到了项目的根目录下。

### ISSUE THREAD

**Issue by arterli** [75team/thinkjs#163]
部署到腾讯云服务器创建目录和文件时，不在www目录下，而是创建到了项目的根目录下。

服务器环境：
发行版本： 	CentOS 6.5 Final
内核版本： 	Linux 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013

**Comment by welefen** [comment]
你是怎么创建目录和文件的呢？

**Comment by welefen** [comment]
你是怎么创建目录和文件的呢？

**Comment by arterli** [comment]
部署到腾讯云服务器创建目录和文件时，不在www目录下，而是创建到了项目的根目录下。
```javascript
   if (!isDir("eee")) {
   fs.mkdirSync("eee");
}
   fs.writeFile("aa.txt", "dfdfs")
```
eee文件夹不会创建到www文件夹里 而是创建在www同级目录下，aa.txt也是

* App
* eee
* node_modules
* www
* aa.txt

**Comment by rekey** [comment]
这个是 node.js 本身的问题，fs.mkdir在各个平台下执行是有差异的。

抹平差异的方式就是你准备一个 绝对路径 给 fs.mkdir 创建。

**Comment by welefen** [comment]
这是环境变量根目录的问题

创建目录最好使用绝对路径

```
fs.writeFile('/path/to/eee');
```

thinkjs里有一些全局变量的路径，具体见：  http://thinkjs.org/doc/appendix.html#系统常量

**Comment by arterli** [comment]
十分感谢，已经解决
解决方案 ： 创建时使用绝对路径。
