### ISSUE TITLE
控制器文件名规则的坑

### ISSUE THREAD

**Issue by leizongmin** [75team/thinkjs#166]
在ThinkJS的文档中，Controller命名方式的描述是这样的：

> 控制器的名称采用驼峰法命名，且首字母大写。

而实际上，假如我有一个Controller的文件名为 `AppCategoryController.js`，访问地址 `/AppCategory`时，在大小写敏感的服务器上运行会提示 `Controller `Appcategory` not found`，将文件名改为`AppcategoryController.js`才解决

而Model里面则是区分大小写的，比如Model的文件名为`AppCategoryModel.js`，则能通过`D('AppCategory')`取得该Model，将文件改名为`AppcategoryModel.js`时则无法取得该Model

希望在ThinkJS中能统一这个命名规则，比如全部不区分大小写，或者是文件名与调用函数时所传递的名字参数一致。

**Comment by welefen** [comment]
多谢建议，会尽快改为驼峰形式

另，2.0设计的时候考虑到了这些问题，已经将所有文件名都改为小写了。

**Comment by welefen** [comment]
已经发布1.2.4版本修复了该问题。

现在访问/AppCategory，对应的Controller为AppCategoryController.js了

**Comment by itchina110** [comment]
哈哈，老雷！
