### ISSUE TITLE
文档watch-compile描述问题

### ISSUE THREAD

**Issue by lucifercd** [75team/thinkjs#182]
npm run watch-compile  这句话的描述

@李成银   建议在文档里加一个说明，要一个终端npm run watch-compile运行，然后另外一个终端npm start  启动。这个对于新手是一个门槛，一开始并不知道要再另外一个终端启动才算项目启动。以为要等npm run watch-compile完成后，再运行npm start  ，结果一直在那里等到起，不知道往下走。

**Comment by welefen** [comment]
https://thinkjs.org/zh-CN/doc/2.0/create_project.html#toc-83f  是觉得这里的描述还有问题么？

**Comment by lucifercd** [comment]
thinkjs new project_path --es6;创建Demo时，创建成功后的提示如下，下面的第三步，用户以为要这步执行完成后，再执行第四步npm start。  结果就卡起了，这个时候可能用户还没有看到你上面回复的文档那个描述。
enter path:
  $ cd demo/

  install dependencies:
  $ npm install

  watch compile:
  $ npm run watch-compile

  run the app:
  $ npm start

**Comment by welefen** [comment]
好的，下个版本会改进

**Comment by liuliangsir** [comment]
![image](https://cloud.githubusercontent.com/assets/8049878/10862564/4926b068-7fe8-11e5-9d1d-557ba634e9ee.png)

**Comment by welefen** [comment]
下个版本（2.0.6）会去掉这个命令，框架会自动编译源代码
