### ISSUE TITLE
[ThinkJS 2.0] hook.js 实际位置和文档描述不一致

### ISSUE THREAD

**Issue by qgy18** [75team/thinkjs#184]
这个问题坑了我好久。2.0 自动创建的目录结构里 `hook.js` 在 `bootstrap` 目录下，文档也是这样描述的。但是调了好久始终不工作，最后发现代码中已经改成从 `config` 目录读取 hook 了：

```
/ququblog2/node_modules/thinkjs/bin/index.js:
  318:   copyFile('bootstrap/hook.js', rootPath + '/hook.js');
```

```
/ququblog2/node_modules/thinkjs/lib/index.js:
  284:     var hookPath = think.THINK_LIB_PATH + '/config/hook.js';
```

**Comment by welefen** [comment]
bootstrap/hook.js 是用来存放一些简单的 middleware 和注册的，是比较容易误解。

下个版本会改名为 middleware.js，同时添加文件 config/hook.js

**Comment by qgy18** [comment]
好吧，果然是这样。2.0 变化还是太大，需要适应适应。
