### ISSUE TITLE
[ThinkJS 2.0] 启用 es6 的项目错误信息不直观

### ISSUE THREAD

**Issue by qgy18** [75team/thinkjs#185]
由于创建项目时加了 `--es6`，代码会被 Babel 实时编译到 app 目录下，导致错误信息提示的行号和位置都是针对编译之后的文件，不直观。

这个问题有什么好的解决方案不？类似于浏览器的 Source Map？

**Comment by welefen** [comment]
Babel 编译时有个保留行号的功能，参数为 `--retain-lines`，可以在 package.json 里 compile 命令下加上这个参数。

这样编译后的文件行号和源文件保持一致，出错后就可以定位到具体的行了。

不过这样编译后的文件代码更不可读，之前因为经常要看编译后的文件代码，所以默认没加这个参数，下个版本可以默认加上这个参数。

**Comment by welefen** [comment]
`2.0.5` 版本创建项目时，可以添加了 ` --retain-lines` 参数。
