### ISSUE TITLE
sqlite的数据库，主键类型是TEXT，用rest时报错

### ISSUE THREAD

**Issue by zh33gl** [75team/thinkjs#188]
sqlite的数据库，主键类型是TEXT，用rest时报错。
action `3b6c279c-bd61-f093-c543-56f9ab4300b7` is not valid. url is `/api/system/3b6c279c-bd61-f093-c543-56f9ab4300b7`

将主键类型改成INT就OK

**Comment by welefen** [comment]
这是因为在解析 url 里的 controller 和 action，不允许含有 `-` 字符，如果 id 值没有 `-` 字符就 OK 了。

另：主键类型肯定要设置为 INT 啊

**Comment by zh33gl** [comment]
特殊原因，设备表的ID都要求用GUID标识。有什么简单的办法可以解决吗？实在不行就只能重写每个controller了

**Comment by welefen** [comment]
暂时可以在 URL 上加一层来解决  /api/system/id/3b6c279c-bd61-f093-c543-56f9ab4300b7

下个版本会解决这个问题。

**Comment by zh33gl** [comment]
OK! 谢谢！！！
