### ISSUE TITLE
怎样截获sqlite返回的内部错误，然后发送给客户端。

### ISSUE THREAD

**Issue by zh33gl** [75team/thinkjs#189]
因数据库里写了好多的触发器，现在想直接将错误返回到客户端。怎么实现？

**Comment by welefen** [comment]
用 ES6 的话，用 try, catch 如：

```js
indexAction(){
   try{
       let data = this.model('user').find();
   }catch(e){this.fail(100, err)}
}
```

用普通方式的话，在 Promise 后面加 catch:

this.model('.user').find().catch(function(err){
   this.fail(100, err)
})

**Comment by zh33gl** [comment]
按你的代码输出的结果是：{"errno":100,"errmsg":{"errno":19,"code":"SQLITE_CONSTRAINT"}}；
其实我想要的结果是控制台打印出来的错误结果：[2015-11-03 14:07:16] [Error] Error: SQLITE_CONSTRAINT: 只能有一个上级域
    at Error (native)

谢谢！！！

**Comment by welefen** [comment]
详细的错误信息在 `err.stack` 里，你可以过滤下再输出
