### ISSUE TITLE
文档中的搜索结果链接问题

### ISSUE THREAD

**Issue by lucifercd** [75team/thinkjs#193]
文档的搜索功能不错，搜索结果如果能够加入锚定点就好了，会方便很多。

**Comment by xuexb** [comment]
> 文档的搜索功能

是指在`thinkjs.org`上doc的搜索？那个是`grep`的吧

**Comment by lucifercd** [comment]
比如：
https://thinkjs.org/zh-CN/doc/2.0/search?keyword=update
点击相应的链接，只能跳转到相应的页面，必须在这个页面cmd+f再搜搜一下才能定位。
这个功能实现可能比较麻烦。

**Comment by welefen** [comment]
恩，现在是用 grep 命令来实现的，实现的比较简单。

**Comment by qgy18** [comment]
可以把 keyword 带到文档页，再在那边加一个 keywork 高亮。我随手找了一段代码，貌似效果还可以：

http://jsbin.com/tudugeyade

On Thu, Nov 19, 2015 at 9:06 AM, Welefen Lee <notifications@github.com>
wrote:

> 恩，现在是用 grep 命令来实现的，实现的比较简单。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/75team/thinkjs/issues/193#issuecomment-157913975>.
>



-- 
非常感谢~

屈光宇（ImQuQu.com）
