### ISSUE TITLE
validation 的配置建议

### ISSUE THREAD

**Issue by dsonet** [75team/thinkjs#199]
https://thinkjs.org/zh-CN/doc/2.0/validation.html#in

入下配置：
export default class extends think.logic.base {
  indexAction(){
    let rules = {
      doc: "string|default:index",
      version: "string|in:1.2,2.0|default:2.0"
    }
  }
}
及
export default class extends think.logic.base {
  indexAction(){
    let rules = {
      version: "in:1.2,2.0" //需要是 1.2，2.0 其中一个
    }
  }
}
等使用了字符串配置，很多情况下这些值是JavaScript变量，因此建议提供键值对的配置方式，比如{type:'string', in: valueIn, default: defValue}，可以很好的解决这个问题（并且比string方式要来的灵活，不容易出错(JS本身的语法检查)，且省去解析字符串的耗时）。

**Comment by welefen** [comment]
多谢建议，在会在 2.0.10 版本中考虑支持

**Comment by welefen** [comment]
已经支持
