### ISSUE TITLE
有否考虑过支持 typescript ？

### ISSUE THREAD

**Issue by jiangyuan** [75team/thinkjs#202]
刚试用了下 2.0 ，感觉不错，尤其是 es6 相关的东西，用的 babel 编译。
既然都已经编译了，有否考虑过支持 typescript ？

**Comment by fegg** [comment]
@jiangyuan  前端部分你可以配置成ts编译。后端thinkjs部分要看成银他们了。不过我上次使用过后，我觉得最好都保持一个开发版本号和技术，这样用起来会统一一点。＝＝万一编译后的结果代码不一样就惨了～

**Comment by welefen** [comment]
@jiangyuan 多谢建议，现在用 TypeScript 还是挺多的，后续会考虑这个功能

**Comment by jiangyuan** [comment]
哈哈。 
@fegg 我们团队有人尝试这样做了，还在评估效果。
