### ISSUE TITLE
使用nginx反向代理，静态资源匹配 建议

### ISSUE THREAD

**Issue by mind029** [75team/thinkjs#206]
使用  nginx 反向代理 nodejs 静态资源匹配需要 更改nginx  写 location ~ xxxx{}  匹配静态资源。
现在thinkjs 官网 只匹配 static，这个目录。建议 把常见的匹配静态文件的正则（我正则比较烂，需要写多个location 。） 写 到配置文件去。
目前我的写法：
location ~ \.(gif|jpg|png|js|css|html)$ {}
location ~ ^/(static/|images/|css/) {}

**Comment by qgy18** [comment]
把静态资源统一放在 static 有很多好处啊，例如之后迁移到 CDN 非常方便。你是基于怎样的考虑，要把静态文件分散存放呢？

**Comment by mind029** [comment]
@qgy18 ，场景是项目有一些历史遗留下来的html文件，这些html数据库没有数据，又不给能删，怕对seo影响不好。路径都是不一样的。所以才提出来

**Comment by qgy18** [comment]
根据后缀判断图片、js、css 倒还好，判断 html 不好弄，因为使用 ThinkJS 的项目推荐使用伪静态化 URL。

例如我的博客：https://imququ.com/post/web-proxy.html 这种 `.html` 结尾的 URL 还是需要交给 Node.js 处理，并不存在这个 html 文件。

**Comment by mind029** [comment]
@qgy18 懂你的意思，可能我这场景有点特别。如果没我这场景 其实 匹配静态文件 js css 图片 到是够了。

**Comment by welefen** [comment]
官方生成的就可以，如果需要对这些资源特殊设置，在最后加个 

```nginx
location / {
   
}
```

就可以了。

不要修改默认生成的：

```nginx
    if ( !-f $request_filename ){
        rewrite (.*) /index.js;
    }
    location = /index.js {
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://127.0.0.1:$node_port$request_uri;
        proxy_redirect off;
    }
```

**Comment by qgy18** [comment]
嗯，找不到的文件就 rewrite 给 index.js，交给 Node.js 去处理。
