### ISSUE TITLE
通过 config 读取配置不一致

### ISSUE THREAD

**Issue by AlphaTr** [75team/thinkjs#207]
通过 think.config 方法读取配置不一致，如下：

配置文件：
```
{
    someConf: 'xxx'
}
```

通过 `think.config().someConf` 可以正常读取，通过 think.config('someConf') 读取失败，查看了下，是下面的 toLowerCase 导致
```
// thinkjs/src/core/think.js 第 497 行
name = name.toLowerCase();
```

建议去掉转换小写，配置读取和设置保持一致

**Comment by welefen** [comment]
恩，会在下个版本种去掉自动转换为小写的逻辑。
