### ISSUE TITLE
view目录更改之后，新建module时没有根据config里面的view目录路径来新建。

### ISSUE THREAD

**Issue by wjs** [75team/thinkjs#212]
把项目根目录的 `view` 目录移到  `assets/view` 目录下，然后， `common/config/view.js` 里面也把路径配置到了 `root_path: think.ROOT_PATH + '/assets/view',` 下。  
但是试用 `thinkjs module admin` 来新建一个 admin 的 module 的时候，是在项目根目录下又新建了 view 目录。  
希望下个版本可以根据 config 里面配置的 view 路径来新建。

**Comment by welefen** [comment]
多谢建议，下个版本可以考虑。

**Comment by welefen** [comment]
2.1 版本已经修复
