### ISSUE TITLE
thinkjs是否考虑将Babel升级到6.x

### ISSUE THREAD

**Issue by lubezhang** [75team/thinkjs#215]
目前是用最新的2.0.11，Babel-runtime是5.6.17，页面端使用Babel6编译react，怎么解决两个Bebel版本冲突的问题，或者升级thinkjs的Babel版本

**Comment by welefen** [comment]
会在下个大的版本里（2.1）会升级到 Babel 6

**Comment by welefen** [comment]
2.1 版本已经升级到 6
