### ISSUE TITLE
2.1 版本功能列表

### ISSUE THREAD

**Issue by welefen** [75team/thinkjs#217]
开始开发 2.1 版本，以下是功能列表，欢迎大家提建议：

* 优化 http 对象生成方式，不用每次都复制 
* 过滤 .svn, .git 之类的文件 
* 支持 TypeScript --ts 属性
* 命令行创建将 --es6 参数改为 next ?
* 使用 Babel 6 ?
* 路由优化，支持缓存，Redirect，直接拒绝等
* runtime 目录移动到 app 平级的目录
* Session 支持服务端直接踢掉某个人？
* Model 增加数据检测
* 路径中 / 在 windows 下替换为 \\
* 将文件 bin/index.js 移动为 src/command.js
* 加强 windows 下测试，避免 windows 下才出现的问题
* 解决 view root_path 修改后，创建文件时的路径问题
* 支持 PostgreSQL 数据库
* 修改现在的 fields 为 scheme
* 添加更多的 where 方法语法糖

预计 1 月中旬发布！

**Comment by jtHwong** [comment]
经测试，Babel6和webpack结合有一些插件不足够稳定。所以不建议升级babel6.

**Comment by welefen** [comment]
@jtHwong 恩，所以这个功能后面会有问号，会先做大量的测试，如果没有问题在切换过去

**Comment by xuexb** [comment]
> 修改现在的 fields 为 scheme

@welefen 是指引用`model`的时候的`fields`（设置字段）方法改成`scheme`吗？

**Comment by welefen** [comment]
@xuexb 恩，是的

**Comment by akira-cn** [comment]
还有国际化支持目录大小写不敏感，现在如果目录是 zh-CN，http头里面是zh-cn就会匹配不到，但是很多第三方库和浏览器插件是不区分大小写的。
