### ISSUE TITLE
数据库连接错误

### ISSUE THREAD

**Issue by qudao** [75team/thinkjs#231]
![image](https://cloud.githubusercontent.com/assets/8510497/12105844/a783ccde-b393-11e5-8fb0-90647311efc9.png)
就是如下错误：
 [Error] Error: ER_ACCESS_DENIED_ERROR: Access denied for user ''@'127.0.0.1' (using password: NO)
我想加上我的用户名aaa密码bbb, 相应文件写在哪？文档未说明。

**Comment by liuguanyu** [comment]
/src/common/config/db.js

**Comment by liuguanyu** [comment]
https://thinkjs.org/zh-CN/doc/2.0/config.html#db
