### ISSUE TITLE
问题：定义一些常量放在那里比较好

### ISSUE THREAD

**Issue by jtHwong** [75team/thinkjs#233]
定义一些常量，以前在python里面单独放个文件夹。
在thinkjs里面，放在src/common/constants

如何方便的在项目导入。

**Comment by welefen** [comment]
可以放在 `src/common/bootstrap/constants.js` 里，`bootstrap` 目录会自动读入，无需手工加载

**Comment by jtHwong** [comment]
ok 多谢
