### ISSUE TITLE
csrf开启了似乎没看到有什么变化

### ISSUE THREAD

**Issue by kaven85** [75team/thinkjs#235]
其他框架开启了 csrf 后，都会生成一个 token，不过 thinkjs 开启后，好像没什么变化？是我配置错误吗？我是在 hook 里加上了logic_before: ["check_csrf"]

**Comment by welefen** [comment]
要设置配置文件  `src/common/config/csrf.js`，里面要开启 CSRF 的功能：

```js
export default {
   on: true
}
```

**Comment by welefen** [comment]
现在 csrf 的 middleware 是默认加的，所以要有一个配置开启。

从 2.1 版本开始，这个 middleware 默认不加，需要手工加，到时候就不用配置了。

**Comment by kaven85** [comment]
原来要这么做。不过官网上都没这块的介绍哦，有可能是我遗漏了，如果真是没有的话，还是希望能补充下

**Comment by welefen** [comment]
文档已经添加，见： https://thinkjs.org/zh-cn/doc/2.1/csrf.html
