### ISSUE TITLE
session以file形式保存遇到登录后提示认证失败的问题

### ISSUE THREAD

**Issue by mrz9** [75team/thinkjs#237]
我的runtime/session目录下存在两个文件，一个是“_"目录的的session（该session是一个过期的session)，还有一个”h“目录下的session（正常未过期的session)。
我现在登录的时候有时遇到登录后跳转到需要session权限验证的请求就提示权限认证失败，
重新登录有时也会出现，有时就不会。
初步怀疑是否session目录下有个过期的session干扰到呢？

ps:最后测试我把浏览器cookies清掉后，”_"该目录文件就自己重建了，然后就正常了，那我怎么操作才能确保退出登录的时候，重新登录时"_"目录下文件会自己重建呢？难道要自己触发清楚cookies吗？

**Comment by welefen** [comment]
无法复现，暂时关闭
