### ISSUE TITLE
希望增加单页面应用调试相关功能

### ISSUE THREAD

**Issue by zl810881283** [75team/thinkjs#239]
最近拿thinkjs + angular2 做单页面应用，纯前端调试倒是无所谓，webpack很方便，但是调试和后台交互数据的时候比较麻烦。调试时有时需要将页面刷新，由于使用router单页面应用会改变请求的url，需要将不同的url返回相同的html静态页面。所以希望内置的静态资源访问服务器可以配置转发规则

**Comment by welefen** [comment]
可以通过自定义路由进行，将一类访问请求命中到一个 Action 下，这样就可以输出同一个模板了。
