### ISSUE TITLE
npm run compile 出错

### ISSUE THREAD

**Issue by peirancao** [75team/thinkjs#245]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'compile' ]
2 info using npm@3.3.12
3 info using node@v5.3.0
4 verbose run-script [ 'precompile', 'compile', 'postcompile' ]
5 info lifecycle wishlist-server@1.0.0~precompile: wishlist-server@1.0.0
6 silly lifecycle wishlist-server@1.0.0~precompile: no script for precompile, continuing
7 info lifecycle wishlist-server@1.0.0~compile: wishlist-server@1.0.0
8 verbose lifecycle wishlist-server@1.0.0~compile: unsafe-perm in lifecycle true
9 verbose lifecycle wishlist-server@1.0.0~compile: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;E:\wishlist\server\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\HashiCorp\Vagrant\bin;C:\MinGW\msys\1.0\bin;C:\Program Files\nodejs\;C:\Program Files\Java\jdk1.7.0_79\bin;%USERPROFILE%\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;D:\tools\Console;C:\Users\peira\AppData\Local\atom\bin;C:\Users\peira\AppData\Roaming\npm
10 verbose lifecycle wishlist-server@1.0.0~compile: CWD: E:\wishlist\server
11 silly lifecycle wishlist-server@1.0.0~compile: Args: [ '/d /s /c',
11 silly lifecycle   'babel --presets es2015-loose,stage-1 --plugins transform-runtime src/ --out-dir app/ --retain-lines' ]
12 silly lifecycle wishlist-server@1.0.0~compile: Returned: code: 1  signal: null
13 info lifecycle wishlist-server@1.0.0~compile: Failed to exec compile script
14 verbose stack Error: wishlist-server@1.0.0 compile: `babel --presets es2015-loose,stage-1 --plugins transform-runtime src/ --out-dir app/ --retain-lines`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid wishlist-server@1.0.0
16 verbose cwd E:\wishlist\server
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile"
19 error node v5.3.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error wishlist-server@1.0.0 compile: `babel --presets es2015-loose,stage-1 --plugins transform-runtime src/ --out-dir app/ --retain-lines`
22 error Exit status 1
23 error Failed at the wishlist-server@1.0.0 compile script 'babel --presets es2015-loose,stage-1 --plugins transform-runtime src/ --out-dir app/ --retain-lines'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the wishlist-server package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     babel --presets es2015-loose,stage-1 --plugins transform-runtime src/ --out-dir app/ --retain-lines
23 error You can get their info via:
23 error     npm owner ls wishlist-server
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by welefen** [comment]
有执行  `npm install` 安装依赖么？

**Comment by peirancao** [comment]
@welefen 执行了

**Comment by peirancao** [comment]
@welefen  从2.0 升级到 2.1

**Comment by welefen** [comment]
从错误信息上看是 Babel 编译的时候报错了，你把 `node_modules` 目录删除调，然后重新安装下试试。

**Comment by peirancao** [comment]
@welefen 好的 应该是win环境下的问题  在 osx上没问题

**Comment by zhuyingda** [comment]
4.x以后没怎么在win环境跑过node程序了，不过之前踩过一个坑 有没有可能是windows环境的反斜杠？ "\"

**Comment by welefen** [comment]
@zhuyingda  2.1 版本里下了很大的功夫解决 windows 下分隔符为反斜杠导致的问题。

现在所有的代码在 windows 下测试也都通过。

**Comment by welefen** [comment]
@peirancao 麻烦提供下你的 windows 版本，Node.js 版本，npm 版本，ThinkJS 版本。  我装个对应的虚拟机测试下。
