### ISSUE TITLE
Mongodb addMany报错，[Error] TypeError: dataList.map is not a function

### ISSUE THREAD

**Issue by SinalVee** [75team/thinkjs#248]
水平渣，我就不乱分析了 - -
这是在node_modules/thinkjs/lib/adapter/db/mongo.js addMany方法中打印的arguments，应该是这里的问题
```
{ '0': { email: 'xxx', name: 'sfd', password: 'xx' },
  '1': { email: 'aaa', name: 'bbb', password: 'ccc' } }
{ table: 'xxx', tablePrefix: undefined, model: 'xxx' }
```

**Comment by welefen** [comment]
要传一个数组进去，你传的是个对象

**Comment by SinalVee** [comment]
@welefen 这个我知道，传的就是数组
```
let model = this.model('xxx');
let added = await model.addMany([{
  x: 'aaa'
}, {
  x: 'bbb'
}]);
```
真的会报错，数据库中存入的值是这样的
```
{ "_id" : ObjectId("569dd2e30dd763661be6bab5"), "0" : { "x" : "aaa" }, "1" : { "x" : "bbb" } }
```

**Comment by welefen** [comment]
多谢反馈，确认是个 bug，已经修复，随下个版本挥发布。

你暂时用 `add` 方法吧。

**Comment by SinalVee** [comment]
好的 :+1: 
另外咨询一下，如果我想在每个model add的时候都自动加一个createdAt和updatedAt，在更新的时候修改updatedAt，应该怎么做？
还有一点不太清楚，为什么add返回的id是object而不是string，如果我要拿这个id查询刚才插入的数据，还要toString()一下才行

**Comment by welefen** [comment]
自动添加的字段可以在 `schema` 里设置，具体见 https://thinkjs.org/zh-cn/doc/2.1/model_intro.html#toc-2d3

更新时自动更新字段功能目前还没有，下个版本会考虑。

id 是 object 的问题我查下。

**Comment by welefen** [comment]
已经在 2.1.4 版本中支持，具体见：https://thinkjs.org/zh-cn/doc/2.1/model_intro.html#toc-2d3

**Comment by SinalVee** [comment]
nice，非常感谢～
