### ISSUE TITLE
debug

### ISSUE THREAD

**Issue by jiangyuan** [75team/thinkjs#255]
以前在 webstorm debug 的时候，直接打个断点方便的很。
现在打个断点发现不行，原来 src 里面的代码是不执行的，你必须去编译后的代码里打断点才行。
有好的解决方式？

**Comment by xunuoi** [comment]
@jiangyuan 有一个方案是可以配合node-inspector来实现服务端node源码断点，用node-inspector打开后，你可以用Chrome的debugger来给源码ES6的node代码打断点、查看源码等。(当然也可以给编译后的代码打断点)。

**Comment by jiangyuan** [comment]
@xunuoi 用了 webstorm ，就真的不再想折腾 node-inspector 。

**Comment by Uter1007** [comment]
I think for such things we would need source maps or ? I created also a ticket for that, cause I am using the typescript support. Would love to use the original ts files for debugging and not the compiled es5 js files.

**Comment by jiangyuan** [comment]
@Uter1007 You understand Chinese ?

**Comment by Uter1007** [comment]
nope ;) But Google Translate FTW  -> sorry if I misinterpreted some stuff ^^

**Comment by welefen** [comment]
ThinkJS 2.2  版本会支持在 WebStorm 里断点调试源代码，会在下周发布（3.31 之前）

**Comment by jiangyuan** [comment]
激动。

**Comment by welefen** [comment]
@Uter1007  It resolved in ThinkJS 2.2, https://thinkjs.org/en/doc/2.2/debug.html
