### ISSUE TITLE
是否能考虑将thinkjs的api名称做下亲和性修改

### ISSUE THREAD

**Issue by xunuoi** [75team/thinkjs#256]
举个例子，现在的ThinkJS的渲染的是display、assign等，名称和调用方式跟传统的express、koa并不一致

可不可以考虑后续版本将api定制修改成贴合传统node web框架的方式？
这样我觉着会方便推广thinkjs，如果是从express转过来的童鞋，几乎不用看文档就能立刻下入手，学习成本进一步降低，会更容易被更多人喜欢和接受

这样大家的关注点也可以更聚焦到es6、typescript等。

**Comment by welefen** [comment]
display 现在已经有了别名方法 `render`

**Comment by SinalVee** [comment]
还有使用mongodb更习惯于findOne查询单条数据，find查询多条数据

**Comment by welefen** [comment]
@SinalVee  这个不会再改，因为 find 表示查询单条数据，修改的话无法向前兼容。

**Comment by xunuoi** [comment]
@welefen 赞！文档好像还没更新～～

render的话最好也可以考虑支持直接允许传递data进去，类似this.render(viewFile, data, cb)类似这种，相当于省一步assign的调用。cb是可选，如果觉着作为回调方式有些丑陋，可以也支持Promise，那就是类似：

```
this.render(viewFile [, data])
.then(html=>{
        // html是模板渲染后的string或者stream，此处可做一些自定义处理
})
```

期待Thinkjs越来越完美！！用的小伙伴越来越多！早日冲向国际嘿嘿
