### ISSUE TITLE
关于文档示例中schema default的疑问

### ISSUE THREAD

**Issue by SinalVee** [75team/thinkjs#257]
```
fullname: { //全名
  default: () => { //first_name 和 last_name 的组合
    return this.first_name + this.last_name;
  }
}
```
因为default只在添加数据时有效，所以我以为这里的`this.first_name`和`this.last_name`都是model.add()中添加的字段，所以按照文档写了下面这些代码
```
nickname: {
  default: () => {
    return this.username;
  }
}
```
然后测试，`module.add({username: 'test'})`，数据库中nickname的值为null，是不能这样用吗？如果是的话，文档示例这种用法要什么情况下使用呢？

**Comment by welefen** [comment]
你用的是 Mysql 还是 MongoDB？

**Comment by SinalVee** [comment]
mongodb

**Comment by welefen** [comment]
知道原因了，这里不能用 Arrow Functions。需要用普通的 function，不然 Babel 编译后 this 有问题。

我更新下文档

**Comment by SinalVee** [comment]
thanks.
