### ISSUE TITLE
运行npm install报错：verbose stack Error: thinkjs@2.0.0 prepublish: `npm run compile`

### ISSUE THREAD

**Issue by zhongw** [75team/thinkjs#259]
210 verbose stack Error: thinkjs@2.0.0 prepublish: `npm run compile`
210 verbose stack Exit status 1
210 verbose stack     at EventEmitter.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
210 verbose stack     at emitTwo (events.js:87:13)
210 verbose stack     at EventEmitter.emit (events.js:172:7)
210 verbose stack     at ChildProcess.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
210 verbose stack     at emitTwo (events.js:87:13)
210 verbose stack     at ChildProcess.emit (events.js:172:7)
210 verbose stack     at maybeClose (internal/child_process.js:818:16)
210 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by zhongw** [comment]
在es6 branch下

**Comment by welefen** [comment]
ES6 branch 已经合并到主干了
