### ISSUE TITLE
thinkjs.org is down

### ISSUE THREAD

**Issue by malixsys** [75team/thinkjs#261]

**Comment by qgy18** [comment]
As a temporary solution, you can add this line to your hosts file:

```
101.198.153.219 www.thinkjs.org
```

**Comment by malixsys** [comment]
101.198.153.219  thinkjs.org

**Comment by xunuoi** [comment]
都有国际友人使用Thinkjs了么？^_^ Pretty Good～

**Comment by zhuyingda** [comment]
You might also need to add this line in your hosts file for static file of the thinkjs.org:
111.206.52.75 p.ssl.qhimg.com
