### ISSUE TITLE
线上部署 pm2 失败

### ISSUE THREAD

**Issue by herro-chen** [75team/thinkjs#269]
node www/production.js 能正常启动
pm2 startOrReload pm2.json 失败
pm2 startOrReload www/production.js 也失败

pm2.json 改了cwd 为绝对路径

**Comment by welefen** [comment]
具体错误信息呢？

**Comment by herro-chen** [comment]
更新了版本之后部署成功

**Comment by ufologist** [comment]
注意 `pm2.json` 中的 `"cwd": "F:/tmp/thinkjs-demo"` 路径必须使用 `/` 来分隔, 否则 PM2 启动会报错: `Error: ENOENT: no such file or directory, uv_chdir`
