### ISSUE TITLE
同一个controller拉取多个第三方api服务接口

### ISSUE THREAD

**Issue by roninliu** [75team/thinkjs#270]
使用thinkjs 拉取多个第三方接口，然后this.assign("sites", site)时，如果return this.display();放在请求外面的话就报错，看了下官方的一个例子：http://www.w3ctech.com/topic/612

直接操作本地的ok，由于第三方的是需要等待回调。。这个的 
this.assign({
        group_list: p1,
        article_list: p2
    })
    return this.display();
p1，p2就难免为空，导致页面无法渲染， 有办法解决么

**Comment by dsonet** [comment]
@roninliu 你用Promise包装一下你的调用接口就可以了

**Comment by welefen** [comment]
p1, p2 必须为 Promise 才可以

**Comment by welefen** [comment]
如果本身是 callback 的方式，可以通过 think.promisify 方法包装成 Promise 方式

**Comment by roninliu** [comment]
多谢各位。已经使用service 和promise方式解决
