### ISSUE TITLE
建议thinkjs增加支持https

### ISSUE THREAD

**Issue by arden** [75team/thinkjs#271]
现在ios开发都要求需要支持https的服务请求，建议thinkjs能够支持https

**Comment by qgy18** [comment]
HTTPS 推荐通过 Nginx 来部署，proxy pass 到 ThinkJS 提供的 HTTP 服务上。

包括 https://thinkjs.org 等很多使用 ThinkJS 开发的网站都是这样部署 HTTPS 服务的。

**Comment by welefen** [comment]
@arden 如 @qgy18 所说，HTTPS 用 Nginx 来部署，创建项目的时候生成的 nginx.conf 文件里有 HTTPS 相关的配置，打开即可。
