### ISSUE TITLE
thinkjs2.1.5版本的fetch问题

### ISSUE THREAD

**Issue by lubezhang** [75team/thinkjs#273]
使用fetch（**isomorphic-fetch@2.2.1**）向后台提交数据，以前都是好的，今天更新了thinkjs2.1.5，发现controller获取不到页面提交的数据了。

经过测试发现只有2.1.5版本存在这个问题，2.1.4、2.1.3、2.1.2都可以正常获取数据。

~~~javascript
async delAction(){
    let articleId = this.post("articleId");

    let affectedRows = await this.model.where({id: articleId}).delete();
    if(_.isNumber(affectedRows)){
      return this.success(affectedRows);
    } else {
      return this.fail("ARTICLE_ADD_FAIL");
    }
    
  }
~~~

**Comment by welefen** [comment]
发送提交数据的接口时，需要发送 Content-Type，可以设置为 `application/x-www-form-urlencoded`

**Comment by lubezhang** [comment]
果然可以了。详细看了Fetch规范，是之前对Fetch规范了解的太少。
还有一个小问题，为什么2.1.5以前的版本，不添加Content-Type这个header就没问题呢？

**Comment by welefen** [comment]
之前默认就会 querystring  解析，但这样会带来其他的问题，所以在 2.1.5 版本里优化了

**Comment by lubezhang** [comment]
问题已解决，多谢回复。
