### ISSUE TITLE
mongo model _id查询时，需要_id 类型必须是string，如果为ObjectID会报错

### ISSUE THREAD

**Issue by zl810881283** [75team/thinkjs#278]
mongo model _id查询时，需要_id 类型必须是string，如果为ObjectID会报错，
查看thinkjs源码发现框架会自动将_id字段转换成ObjectID，如果传入已为ObjectID，就会报错。
建议将增加类型检测，已为ObjectID时，框架不再做转换
```javascript
let ObjectID = require('mongodb-core').BSON.ObjectID;
//........
let _id=ObjectID('56ce91f066acd0639ff016e4');
//报错
await model.where({_id: _id}).find();
//ok
await model.where({_id: _id.toString()}).find();
```

**Comment by welefen** [comment]
多谢建议，下个版本会修复这个问题。

不过查询的时候没必要手动转成 ObjectId 去查啊，框架会自动转的。

**Comment by zl810881283** [comment]
这个需求主要出在mongo表关联上，一个表包含另外一个表的_id，存的时候会将ObjectID类型存入表中，取出来再做查询的时候就是ObjectID类型

**Comment by welefen** [comment]
https://github.com/75team/thinkjs/commit/6fcda87ff61a03127f91d6ef2db9213bbe81a670 该次提交中修复了该问题

**Comment by LeeJim** [comment]
其实我发现还有另外一个问题。
如果我的key不是_id，但是我的value值是ObjectId类型的，框架也不会自动帮我转换。
