### ISSUE TITLE
页面命名不美观 得写多长的名字啊 XXXXXXXXXXXXXXX_WWWWWWWWWWWW.html 疼

### ISSUE THREAD

**Issue by Messilimeng** [75team/thinkjs#279]

**Comment by welefen** [comment]
你是觉得 `user_detail.html` 这种文件名太长了？

可以把分隔符换成 `/`，这样就成为 `user/detail.html` 了，具体请见： https://thinkjs.org/zh-cn/doc/2.1/question.html#toc-aca
