### ISSUE TITLE
Typescript + Node-Inspector + SourceMaps

### ISSUE THREAD

**Issue by Uter1007** [75team/thinkjs#282]
HI I am pretty new to thinkjs, 

I would like to know if I can use the normal compile.js to work with sourcemaps for typescript support in node-inspector. Currently I can use node-inspector but all typescript src files are not available, only the compiled javascript can be debugged. 

Do I need to change to gulp to build my own workflow ? 

Cheers, 
Uter

**Comment by welefen** [comment]
It will be resolved in ThinkJS 2.2, it will released in next week(before 3.31)

**Comment by welefen** [comment]
@Uter1007 It resolved in ThinkJS 2.2, https://thinkjs.org/en/doc/2.2/debug.html
