### ISSUE TITLE
pathname_suffix 问题

### ISSUE THREAD

**Issue by wangchenhao** [75team/thinkjs#286]
我在使用`thinkjs`过程中发现 配置中的 `pathname_suffix`属性只能 去除 单一的 后缀，想确认下是不是。还是可以写成 `array` 格式 去除多个！

**Comment by wangchenhao** [comment]
`thinkjs`文档中有许多地方用到 `timeout`都是以秒为单位？

**Comment by welefen** [comment]
pathname_suffix 现在只能是字符串，你那边为什么有 array 格式的需求呢？

ThinkJS 所有涉及时间的配置单位都是 秒

**Comment by wangchenhao** [comment]
我这里需要过滤多个 后缀。所以想要 可以是array格式的，昨晚想了下，想自己弄个中间件 解决下。

**Comment by welefen** [comment]
恩，系统默认的也是通过中间件完成的。你重新弄下中间件就可以了。

https://thinkjs.org/zh-cn/doc/2.1/middleware.html#toc-df6
