### ISSUE TITLE
group 中存在逗号时出错的问题

### ISSUE THREAD

**Issue by ymma** [75team/thinkjs#290]
## DESC
let group = "date_format(create_time,'%Y-%m-%d')"
model.group(group)

却生成了：
![错误](http://t35-4.yunpan.360.cn/p1/800-600.d6928ff3ddef2b4d539262c502bdccef32dab2b0_fszt_35_fszt1_t.6791c0.jpg?st=QFfQkJKQUa0le1u8SXgm4A&e=1457712000&mt=)

逗号后面 不应该有`

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
Fix with https://github.com/75team/thinkjs/commit/8d5ad988497581a6d6e79d265cf512b48531a912 commit
