### ISSUE TITLE
用postgresql且字段是boolean时，调用model.add出错

### ISSUE THREAD

**Issue by defans** [75team/thinkjs#292]
其true值现在是 1， 应该为‘1’或者TRUE
看了一下源代码：
adapter/db/_parse.js中的parseValue(value)处:
}else if(think.isBoolean(value)){
      value = value ? '1' : '0';
    }
adapter/db/base.js中的add方法处:
if (think.isString(val) || think.isBoolean(val) || think.isNumber(val)) {
        values.push(val);
这个应该是和其他数据库不兼容的地方

**Comment by welefen** [comment]
已经修复，见： https://github.com/75team/thinkjs/commit/13b510dd208e28092f5f0f425eacb7f1b64957ed
