### ISSUE TITLE
thinkjs 关联查询 relation 的问题

### ISSUE THREAD

**Issue by YoRolling** [75team/thinkjs#293]
## DESC
关联查询Belong to 的时候关联键为undefined
`

    init() {
        this.super('init', arguments);     

        this.relation = {  

            user: {  

                type: think.model.BELONG_TO,  

                model: "user",  //  关联用户表

                name: "user_id",  

                key: "uid",   // 当前模型外键关联字段是UID
 
                fkey: "id"   // 用户表对应的是主键ID

            }  

        }  

    }
`

控制台SQL 

`    SELECT * FROM tbl_ugames WHERE ( 'hashKey' = 'c9510277708a62' ) 1ms `

`SELECT * FROM tbl_user WHERE ( 'id' = undefined ) 1ms `

烦请解答，tks~~ ;-)
## ENV

Platform: win10 64

Node.js Version:4.1.1

ThinkJS Version: 2.1.7

**Comment by welefen** [comment]
字段 name 设置错误，具体见： https://thinkjs.org/zh-cn/doc/2.1/model_relation.html#toc-539

其他字段根据数据表也检查下。

**Comment by YoRolling** [comment]
@welefen  Hi，首先非常感谢您的回答。感觉还是不太清楚这个 `name` 究竟指的什么，如果有时间的能否详细讲解一下。
另外感觉官网上这些如果能放上model定义 和数据库表结构这样对比来学习可能对我们这些新手更友善一些，当然这是个人感觉。

最后再次感谢您在百忙之中回答，tks。

**Comment by welefen** [comment]
不好意思，上面写错了。是 fkey 写错了，应该为 fKey。

请确认下 ugames 表有 uid 字段，user 表有 id 字段，并且这 2 个字段是关联的。

**Comment by LaPoPvLe** [comment]
model\relation.js 

 async _getBelongsToRelation(data, mapOpts/*, options*/){
//获取(where $1 $2)
    mapOpts.key = mapOpts.model.getModelName() + '_id';
    mapOpts.fKey = await mapOpts.model.getPk();
    let where = this.parseRelationWhere(data, mapOpts);
    let mapData = await mapOpts.model.where(where).select();
    return this.parseRelationData(data, mapData, mapOpts);
  }

//获取(where $1 $2) 其中$2是根据data的类型确定是=还是IN操作, 但是$1因为上面的方法是固定取模型的getModelName() + '_id'的模式, 所以是固定的. 
parseRelationWhere(data, mapOpts){
    if (think.isArray(data)) {
      let keys = {};
      data.forEach(item => {
        keys[item[mapOpts.key]] = 1;
      });
      let value = Object.keys(keys);
      return {
        [mapOpts.fKey]: ['IN', value]
      };
    }
    return {
      [mapOpts.fKey]: data[mapOpts.key]
    };
  }

所以原本配置项里的key其实没有用到
不知道是我理解错了, 还是bug
假设场景
用户A给用户B发了个消息存在消息表中(t_message), 用户在(t_user)
为了保存这个消息:
t_message: id, from_user_id, target_user_id, content
t_user: id, nickname

一个message模型, relation中有(from_user, to_user), 按照我的理解应该是BELONG_TO关系, 但是
fKey是固定读取关联模型的getModelName()的, 那我关联的本地key必须是user_id(如果t_user对应模型名称是user), 那我2个关联模型的逻辑怎么写呢

**Comment by welefen** [comment]
这里确实有问题

**Comment by welefen** [comment]
https://github.com/75team/thinkjs/commit/d1601cc910f2840821b22effce7c4e1c2d0cd889  已经修复
