### ISSUE TITLE
代码编译出现一次语法错误后，代码热更新失效

### ISSUE THREAD

**Issue by dyw934854565** [75team/thinkjs#294]
## DESC
新建的ES6项目
代码编译出现一次语法错误后，代码能正确的自动编译，但是代码热更新失效了。

## ENV

Platform: windows7

Node.js Version: 4.2.1

ThinkJS Version: 2.1.5

**Comment by welefen** [comment]
已经修复，见：https://github.com/75team/thinkjs/commit/d30d9fcf5bca307fbb1248e3bff6548dd904cb0b

体现在当一个文件出现编译错误时，如果编辑还是有错误会导致这个问题。
