### ISSUE TITLE
proxy_on设置为true，但是还是可以直接通过ip+端口访问

### ISSUE THREAD

**Issue by hongbinfu** [75team/thinkjs#296]
## DESC

proxy_on设置为true，但是还是可以直接通过ip+端口访问
ps:无论是env里面的配置还是common下的config文件，设置此项为true并没有文档所说的效果

## ENV

Platform: osx or linux

Node.js Version: 5.9.0

ThinkJS Version: 2.1.8

**Comment by welefen** [comment]
需要注册对应的 middleware 才可以，具体见： https://thinkjs.org/zh-cn/doc/2.1/force_proxy.html

**Comment by hongbinfu** [comment]
![image](https://cloud.githubusercontent.com/assets/9970390/13876444/4f1f7d82-ed3f-11e5-8753-74957639f52b.png)
hook有设置啊，还是可以通过ip+端口访问

**Comment by hongbinfu** [comment]
good
