### ISSUE TITLE
需要自己处理 this.http.req 上的 data 和 end 事件，该怎么做

### ISSUE THREAD

**Issue by andot** [75team/thinkjs#301]
我看源码里面，在 

https://github.com/75team/thinkjs/blob/master/src/core/http.js#L111

里面已经解析了请求的数据，这样我就不能自己处理  this.http.req 上的 data 和 end 事件了，这样，一些直接处理 nodejs 的 req，res 的程序，就无法跟 thinkjs 集成了。

有没有办法可以跳过这一步，让用户代码自己处理这部分？

**Comment by welefen** [comment]
请求处理系统内置的也是通过 middleware 处理的，要自定义处理的话可以添加个 middleware 就可以了。

具体请见： https://thinkjs.org/zh-cn/doc/2.1/middleware.html#toc-49e 里的 `payload_parse`

**Comment by andot** [comment]
谢谢，我试试看。
