### ISSUE TITLE
有推荐的关于角色、权限的中间件吗

### ISSUE THREAD

**Issue by xueyuchen** [75team/thinkjs#304]
## DESC

role、allow action

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by xueyuchen** [comment]
## transform-decorators-legacy
能增加修饰器的编译插件吗

**Comment by welefen** [comment]
添加编译插件可以参见文档： https://thinkjs.org/zh-cn/doc/2.2/question.html#toc-846

**Comment by welefen** [comment]
权限验证这块暂时还没有
