### ISSUE TITLE
TS IDE

### ISSUE THREAD

**Issue by willin** [75team/thinkjs#305]
## DESC
你们用什么IDE进行TS开发？
Atom，WebStorm，Sublime还是Visual Studio？
以及是否在Windows环境下开发？

## ENV

Platform:
OS X 10.11.4

Node.js Version:
5.9.0

ThinkJS Version:
2.2.1

**Comment by willin** [comment]
我现在用的Mac + Atom，但是你懂的，iPad Pro 不能装 os x。。。携带不便想弄个surface pro

**Comment by itchina110** [comment]
surface pro  win 10  也可以装 Atom呀

2016-04-01 17:24 GMT+08:00 Willin Wang <notifications@github.com>:

> 我现在用的Mac + Atom，但是你懂的，iPad Pro 不能装 os x。。。携带不便想弄个surface pro
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/75team/thinkjs/issues/305#issuecomment-204326539>
>



-- 
此致

Mr. Zhou YuBo - 周裕波

 邮件：itchina110@gmail.com

**Comment by willin** [comment]
你们用的什么IDE，我试过好多个，都无法对thinkjs有很好的定义跳转支持

比如 `think.promisify`  无法用 command+鼠标左键进行跳转

**Comment by willin** [comment]
介绍里说

> 支持断点调试 ES2015+ 项目

用的什么工具？ @welefen

**Comment by qgy18** [comment]
https://thinkjs.org/zh-cn/doc/2.2/debug.html

官方文档里有三种不同的调试方法。

On Fri, Apr 22, 2016 at 9:21 PM, Willin Wang <notifications@github.com>
wrote:

> 介绍里说
>
> 支持断点调试 ES2015+ 项目
>
> 用的什么工具？ @welefen <https://github.com/welefen>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/75team/thinkjs/issues/305#issuecomment-213426335>
>



-- 
非常感谢~

屈光宇（ImQuQu.com）

**Comment by welefen** [comment]
@qgy18  说的对，其他编辑器如果支持 SourceMap，那么也是可以断点调试的。
