### ISSUE TITLE
logic int问题

### ISSUE THREAD

**Issue by xuexb** [75team/thinkjs#306]
## DESC

设置logic字段为`int`，如：

```js
this.rules = {
    page: 'int|default:1',
    pageSize: 'int|default:10',
    id: 'int',
    aaa: 'int'
}
```

控制器里：`console.log(this.get())`，访问时不带任何`GET`参数，打印的`id`和`aaa`居然是`NaN`，如：

```
{ page: 1, pageSize: 10, id: NaN, aaa: NaN }
```

理论上应该是`undefined`的吧？

## ENV

Platform: osx

Node.js Version: v4.4.0

ThinkJS Version: v2.1.8

**Comment by xuexb** [comment]
刚升级了下 thinkjs 到 2.2.1也同样存在该问题～

**Comment by welefen** [comment]
因为定义为 int，所以自动做类型转换。值为空的话转成 NaN

**Comment by xuexb** [comment]
@welefen 但我没有`required`必选说明啊，我为空也转么。。。

**Comment by welefen** [comment]
现在是的，类型转换跟是否有 required 无关。

**Comment by xuexb** [comment]
额。。。好吧，那我自己判断处理下吧～

**Comment by welefen** [comment]
恩，你先处理下。后续可以考虑优化下
