### ISSUE TITLE
listAction无法匹配到

### ISSUE THREAD

**Issue by binlaniua** [75team/thinkjs#310]
## DESC
/xx/list 无法匹配到 xx里面的 listAction 

listAction是关键词吗

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
能贴下你的具体代码么？

**Comment by binlaniua** [comment]
大概知道是什么问题了, 是不是controller里面的index.js只能匹配根路径或者/, 我是在index.js里面加个listAction, 然后页面报 ```controller `list` not found```

test/controller/index.js
```
'use strict';

import Base from './base.js';

export default class extends Base {

  async indexAction () {
    this.json('ok');
  }

  async listAction () {
    let DB = this.model('db'),
      dbs = await DB.select();
    this.json(dbs);
  }

  async aaAction (){
    this.json('ok2');
  }
}
```

然后我访问 /test/list 报404， 差不多就是controller里面的index.js只能匹配到/或者跟, 如果要其他的, 得创建响应的controller

**Comment by binlaniua** [comment]
模块其实就是把路由分组了是吧

**Comment by binlaniua** [comment]
刚刚试了下，果然，这个真是太帅了
