### ISSUE TITLE
继承think.controller.rest后  不再执行对应的logic了吗？

### ISSUE THREAD

**Issue by xueyuchen** [75team/thinkjs#311]
## DESC

1、继承think.controller.rest后  不再执行对应的logic？
2、继承think.controller.rest后  不能再自定义Action？

## ENV

Platform:

Node.js Version:

ThinkJS Version: 2.1.5

**Comment by xueyuchen** [comment]
# 继承think.controller.rest后，都不能走自定义的路由了？！！

**Comment by welefen** [comment]
可以走自定义路由，但最后解析会走 REST 特殊的方式。

REST 方式下只有 getAction, postAction, putAction, deleteAction 分别对应增删改查，对应的 logic 也是这几个方法。

建议你先看下 REST API 的具体解释。

**Comment by xueyuchen** [comment]
REST模式能够增加自定义action功能吗？

**Comment by welefen** [comment]
不能。

可以在 Action 里通过参数来判断，如： 加个 type 参数

**Comment by xueyuchen** [comment]
@welefen 
是不是考虑rest controller也可以自定义Action?

**Comment by welefen** [comment]
@xueyuchen 那就不是 REST 了
