### ISSUE TITLE
如何进行复杂查询

### ISSUE THREAD

**Issue by ymma** [75team/thinkjs#321]
## DESC
比如：t=2 and (a>0 or b>0 ) and (c>0 or d>0)

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
可以用复合查询，见： https://thinkjs.org/zh-cn/doc/2.2/api_model.html#toc-f4d

如果非常复杂的话，那就直接写 SQL 语句吧。

**Comment by ymma** [comment]
好吧，谢谢了
