### ISSUE TITLE
logic校验字段，如果require=false，还是会校验参数类型

### ISSUE THREAD

**Issue by xueyuchen** [75team/thinkjs#325]
## DESC
export default class extends think.logic.base {

```javascript
  postAction() {
    this.allowMethods = 'post';
    this.rules = {
      email: 'email',
      username: 'string',
      password: 'string',
      realName: 'string',
      liaisingEditorId: 'string',
      provideWay: 'array',
      provideWayNote: 'string',
    };
  }
}
```
例如校验provideWay字段，如果require=false，但是如果有值则需要为array。
在没有传递provideWay参数时，还是会判断是否为array？

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by FuDengrong** [comment]
我也遇到这个问题了，就是有些参数可有可无，需要有则验证，无则过滤掉，但是logic里面定义了之后，没有传值也会校验。请问你这个问题解决了么，如果解决了能否告知，谢谢！
