### ISSUE TITLE
csrf模块，针对Ajax请求，也应区分Get和Post

### ISSUE THREAD

**Issue by UtillYou** [75team/thinkjs#329]
## DESC

csrf模块，针对Ajax请求，也应区分Get和Post

## ENV

Platform:Windows

Node.js Version:4.2.4

ThinkJS Version:2.2.1

我查看midware中的csrf模块源代码时，发现将Ajax和Post，jsonp请求都做csrf验证。然而事实上一般来讲，ajax也分get和post的，在get时不需要csrf验证。

**Comment by zuoyanart** [comment]
get也是需要的

**Comment by UtillYou** [comment]
从逻辑上讲get只是请求内容，并不涉及安全问题啊

**Comment by welefen** [comment]
恩，GET 是可以不用验证的，下个版本会修复这个问题

**Comment by zuoyanart** [comment]
很多漏洞都是人为的漏洞，乌云上也有相关的实例，我的建议还是严格比较好
