### ISSUE TITLE
windows git-bash 颜色输出问题

### ISSUE THREAD

**Issue by snadn** [75team/thinkjs#330]
因 windows 的 git-bash 中 process.stdout.isTTY 判断的原因，导致 git-bash 中的日志没有颜色。

通过 `colors.enabled = true;` 可以强制输出颜色。

**不知道将 `colors.enabled = true;` 交给 thinkjs 做好，
还是在 development.js 中做好，
还是干脆用户有需要的时候自己在 development.js 中添加的好？**

目前我自己在 development.js 中添加
```
var colors = require('colors/safe');
colors.enabled = true;
```
解决了该问题。

追加：另一个项目在development.js 中设置 `colors.enabled = true;` 无效，设置 `process.stdout.isTTY = true;` 才行

**Comment by welefen** [comment]
多谢反馈，下个版本会优化

**Comment by welefen** [comment]
https://github.com/75team/thinkjs/commit/7538319c4e771d0907e23a90ef3a8298b7d4356d
