### ISSUE TITLE
静态路由Bug

### ISSUE THREAD

**Issue by starriv** [75team/thinkjs#331]
## DESC
以下规则路由，用静态方式写会出现访问任何一个都会返回indexAction 返回的信息.

正则路由
```
export default [
    [/^account$/, "user"],
    [/^account\/login$/, "user/login"],
    [/^account\/signup$/, "user/signup"]
]
```
静态路由
```
export default [
    ["account", "user"],
    ["account/login", "user/login"],
    ["account/signup", "user/signup"]
]
```

## ENV

Platform: OSX 10.11.4

Node.js Version:4.1.0

ThinkJS Version:2.2.x

需要复现的话，Code：https://git.coding.net/starriv/myApp.git

**Comment by welefen** [comment]
这个就是这样的，需要把更精细的匹配放在前面
