### ISSUE TITLE
路由解析出的action为中文时,空操作__call调用失败

### ISSUE THREAD

**Issue by Smallpath** [75team/thinkjs#334]
## DESC
例如:  localhost:8360/f/综合版  
直接返回400 bad request 错误,空操作` __call()`没有被调用  
提示信息`action %E7%BB%BC%E5%90%88%E7%89%88 is not valid. url is /f/%E7%BB%BC%E5%90%88%E7%89%88`

### UPDATE
看了一下源码,在`action not valid`的时候,think.js直接用`think.prevent()`阻止了后续代码的执行

## ENV

Platform:Windows 10

Node.js Version: v5.6.0

ThinkJS Version:v2.2.1

**Comment by welefen** [comment]
这个是为了安全，会校验解析 action 的合法性。 这种情况最好使用自定义路由来处理，不然在 __call 里还要自己去解析 pathname 上的参数。

**Comment by Smallpath** [comment]
目前正在写一个中文论坛,准备直接用中文来直接展示板块的名称,板块目前有三十多个,而且可能会随时增加删除,自定义路由实在不大方便,我建议think.js添加一下中文action的支持

**Comment by welefen** [comment]
这个板块再多配置一个路由就可以了啊，如：

//src/common/config/route.js

```js
export default [
  [/f\/(.*?)/, 'index/cate?name=:1']
]
```

**Comment by Smallpath** [comment]
原来如此,感谢

已解决
