### ISSUE TITLE
redis、数据库 集群操作

### ISSUE THREAD

**Issue by noonhorse** [75team/thinkjs#339]
## DESC
多进程情况下 think.cache  调用 socket  连接 无法保证 redis 等数据库操作的原子性。建议 支持  Cluster, Sentinel, Pipelining 等方式
现在只能用ioredis 来操作

## ENV
all

Platform:all

Node.js Version: all

ThinkJS Version:all

**Comment by ckken** [comment]
```
/**
 * 全局加载 redis 集群
 */
let redis_config = think.config('redis')
let Cls = require('ioredis');
let cluster = new Cls.Cluster(redis_config);
global.redis = Promise.promisifyAll(cluster);
```

**Comment by noonhorse** [comment]
我用的是ioredis 的 sentinels 哨兵机制来处理的
