### ISSUE TITLE
國際化部分是否支援變數加入？

### ISSUE THREAD

**Issue by liaosankai** [75team/thinkjs#341]
## DESC
你好，請問[国际化](https://thinkjs.org/zh-cn/doc/2.2/i18n.html)的部分是否有變數加入用法？

例如：

    // src/common/config/locale/en.js
    export default {
      "greeting": "hello! :name",
    }

    // src/common/config/locale/zh.js
    export default {
      "greeting": "你好! :name",
    }

視圖：

    <%= _("greeting", "陳大明")%>

輸出：

    你好！陳大明

## ENV

Platform: windows10

Node.js Version: v5.11.0

ThinkJS Version: v2.2.1

**Comment by liaosankai** [comment]
抱歉，已發現並測試有同 http://sailsjs.org/documentation/concepts/internationalization 的支援

**Comment by welefen** [comment]
恩，是支持的，完善了下文档： https://thinkjs.org/zh-cn/doc/2.2/i18n.html#toc-24a
