### ISSUE TITLE
檔案路徑在 window 上的問題

### ISSUE THREAD

**Issue by liaosankai** [75team/thinkjs#344]
## DESC
在 windows 数据库使用 sqlite 類型，設定路徑檔案會錯誤。

    exports.default = {
        type: 'sqlite',
        adapter: {
            sqlite: {
                "path": 'database/db.sqlite'
            }
        }
    };

最後產生的檔案位置變成 `database/db.sqlite/.sqlite`，而若使用預設路徑，產生的檔案為 `runtime/sqlite/.sqlite` 而不是文件所說的 `src/common/runtime/sqlite`

## ENV

Platform: Windows 10

Node.js Version: v4.4.3 LTS

ThinkJS Version: v2.2.2

**Comment by welefen** [comment]
如果生成在 runtime 目录的，path 值保留为空就可以了。

最终生成的路径为 config.path + '/' + config.databse + '.sqlite'，如果配置其他路径的话，可以向下面的配置：

```js
exports.default = {
    type: 'sqlite',
    adapter: {
        sqlite: {
           "database": "test",
            "path": 'path/to/sqlite/'
        }
    }
};
```
这样的配置最终生从路径为：path/to/sqlite/test.sqlite

**Comment by liaosankai** [comment]
了解，所以會產生「.sqlite」，是因為少了 `database` 這個參數，希望能在文件上加註一下。

另外想順便請問一下，`prefix` 這個參數也適用於 sqlite 類型的參數嗎？例如：

```js
export default {
    "type": 'sqlite',
    "adapter": {
        "sqlite": {
            "prefix": "myprefix_",
            "database": "mydb"
        }
    }
};
```

**Comment by liaosankai** [comment]
自己試了一下，`prefix` 也能作用。謝謝你
