### ISSUE TITLE
自定义 logic 校验 header 中的数据

### ISSUE THREAD

**Issue by llqgithub** [75team/thinkjs#345]
## DESC

在用 get 或 post 传值时，有时需要在header 里存放一个类似token 的变量，而在logic 里只能校验 get，post 等传过来的变量，而不能校验 header 中的变量。
嗯，我指的是rules，的validate 的那种校验形式。举个栗子：
``` javascript
this.rules = {
  token_xyz: 'token|required:in_header'
};
```
比如自定义成这样，类型是 **token** 类型，自定义的，然后，该变量是必须存在于 **header** 中。
所以，我尝试自定义validate，来校验header 中的变量是否正确。
但问题是，自定义 think.validate 的那个全局代码段的地方，获取不到http 属性，也就是说，没办法取得header 中的数据。希望能有一个解决方案:P

## ENV

Platform: Mac os

Node.js Version: 5.10

ThinkJS Version: 2.2.2

**Comment by welefen** [comment]
暂时不能。

会在下个版本支持该功能（2.2.3），支持方式为：

```
this.rules = {
    name: {
      required: true,
       value: this.header('xxxx')
    }
}
```

具体实现方式见： https://github.com/75team/thinkjs/commit/2bae4c12bbb5d1b8764b25d4b1f68f1d562b3988

**Comment by welefen** [comment]
2.2.3 版本已经发布，欢迎更新使用。
