### ISSUE TITLE
是否能在 Rest 控制器擴增其它 Action ？

### ISSUE THREAD

**Issue by liaosankai** [75team/thinkjs#346]
## DESC
目前 Rest 控制器似乎固定對應 getAction, postAction, putAction, deleteAction 。請問如果打算在 Rest 控制器裡面，處理有多個以上不同的 POST 或 PUT。應該如何去實作呢？例如：

```js
export default class extends think.controller.rest {
  
  * postAction(){
      // POST `media`
  }
  * postMkdirAction(){
      // POST `media/mkdir`
  }
  * postUploadAction() {
      // POST `media/upload`
  }
  * putRenameAction() {
      // PUT`media/rename`
  }
}
```

目前從文件上看來只能從路由去自訂，是這樣嗎？

## ENV

Platform: window-10

Node.js Version: v4.4.3-LTS

ThinkJS Version: v2.2.2

**Comment by welefen** [comment]
这种并不符合标准的 REST API 规范，所以 ThinkJS 现在并不支持。

可以通过自定义路由来完成这个功能，如：

```js
export default [
   [/media\/(mkdir|upload|rename)/, 'media?type=:1']
]
```
这时候在 postAction 或者 putAction 里通过参数 `type` 来获取值，然后这个参数判断执行对应的逻辑。

**Comment by liaosankai** [comment]
了解，感謝你的回覆
