### ISSUE TITLE
mongo model的update方法无法使用 $inc,$addToSet等操作

### ISSUE THREAD

**Issue by hongbinfu** [75team/thinkjs#347]
## DESC
mongo model的update方法无法使用 $inc,$addToSet等操作

```javascript
 testModel.where({"_id":id}).update({ "$inc" :{ "readCount":1 } }
```
同样的写法，同样的mongo模块版本（2.1.18），`thinkjs2.1.8`正常，`thinkjs2.2.3`报以下错误
`
  The dollar ($) prefixed field '$inc' in '$inc' is not valid for storage
`
## ENV

Platform: MAC

Node.js Version: 5.8.0

ThinkJS Version:2.2.3

**Comment by welefen** [comment]
在 3.0.4 版本中测试正常，应该跟 mongo 的版本相关

**Comment by ekongsdk** [comment]
确实存在该问题，thinkjs@2.2.2版本开始出现这个问题，现在我用thinkjs@2.2.1不会出现该问题，麻烦请核对一下这个问题影响挺大的

**Comment by welefen** [comment]
model 里有定义 schema 么？

**Comment by hongbinfu** [comment]
有定义，现在退到thinkjs2.2.1使用正常，thinkjs最新版本就有这个问题




在 2016-06-13 15:11:44，"Welefen Lee" <notifications@github.com> 写道：


model 里有定义 schema 么？

**Comment by welefen** [comment]
麻烦把具体的 schema 贴下

**Comment by hongbinfu** [comment]
貌似没啥特别~_~




在 2016-06-14 15:37:24，"Welefen Lee" <notifications@github.com> 写道：


麻烦把具体的 schema 贴下

**Comment by welefen** [comment]
我这边一直无法复现这个错误，请通过下面的方式帮忙定位下。

编辑文件 `thinkjs/lib/model/_base.js`, 找到代码 `ret = _think_validate2.default.values(ret);`，在这个后面加上 `console.log(ret)`，然后重启服务，访问下看这里打印出来的值是否是 `{ "$inc" :{ "readCount":1 }`

**Comment by welefen** [comment]
这个问题现在还存在么？麻烦把详细的错误提供下

**Comment by welefen** [comment]
知道你的情况了，应该是 schema 里配置的字段有的设置了默认值，并且加了 `update: true`，这样更新的时候自动会带上这个字段导致的报错。

**Comment by welefen** [comment]
下个版本会支持忽略默认值的方式，如：

```js
this.model('xxx').update({'$inc': {}},  true); // 第二个参数为 true 表示忽略默认值
```
