### ISSUE TITLE
PostgreSQL 释放连接，归还给连接池

### ISSUE THREAD

**Issue by UtillYou** [75team/thinkjs#349]
## DESC
我们在生产环境中使用PostgreSQL，发现每过一段时间就会出现这样的错误，导致系统无法运行

`Error: This socket has been ended by the other party`

初步排查了一下代码，发现thinkjs中没有调用node-postgres提供的done()方法归还连接。是否可能是这个问题？
## ENV

Platform:CentOS 7

Node.js Version:4.4.3

ThinkJS Version:2.2.2

**Comment by UtillYou** [comment]
参见
[https://github.com/brianc/node-postgres#client-pooling]

**Comment by UtillYou** [comment]
[https://github.com/75team/thinkjs/blob/master/src/adapter/socket/postgresql.js#L73](设置done的别名)
这段代码，done这个方法是不是指向的不对？
是否应该这样写？
```javascript
this.release = client.done;
```

**Comment by UtillYou** [comment]
进一步查找发现是连接的重连问题，尝试把
[https://github.com/75team/thinkjs/blob/master/src/adapter/socket/postgresql.js#L38](设置连接空闲时间)
的代码注释掉就能每30秒重现问题，不用我之前等8个小时了。
不过解决方案还在研究中

**Comment by welefen** [comment]
应该是连接断开后并没有触发对应的 error 事件导致的，我们追查下。

**Comment by UtillYou** [comment]
我找到原因了
你这个代码判断的额是“This socket is closed.”
而实际上的错误信息是“ This socket has been ended by the other party”
所以没触发，而且你这样通过错误信息判断，也太不靠谱了，底层模块随便改一下错误信息就不好使了

**Comment by UtillYou** [comment]
建议根据错误码
` code: 'EPIPE'`
来判断

**Comment by welefen** [comment]
恩，能否帮忙改下，发个 pull request 呢？

**Comment by UtillYou** [comment]
已发

**Comment by welefen** [comment]
已经合并，多谢！
