### ISSUE TITLE
经常出现500错误

### ISSUE THREAD

**Issue by rindybo** [75team/thinkjs#353]
## DESC
如果站点闲置几分钟没有访问，就会报500错误，如下：
Connection reset. http://www.thinkjs.org/doc/error_message.html#econnreset
试过timeout设为0也不行
再刷新一次又正常了
## ENV

Platform:

Node.js Version:
4.2
ThinkJS Version:
2.2.x

**Comment by welefen** [comment]
应该是你服务器的问题，你的服务器用的是什么呢？

**Comment by rindybo** [comment]
百度云的 bce

**Comment by welefen** [comment]
看下是不是百度云里做了服务没访问时给挂起了

**Comment by rindybo** [comment]
好的 谢谢
