### ISSUE TITLE
全局安完thinkjs，未找到thinkjs命令

### ISSUE THREAD

**Issue by iq9891** [75team/thinkjs#357]
## DESC

运行 

`npm install thinkjs@2 -g`

之后

`└─┬ thinkjs@2.2.3
  ├─┬ babel-runtime@6.6.1
  │ └── core-js@2.4.0
  ├── bluebird@3.3.5
  ├── co@4.6.0
  ├── colors@1.1.2
  ├─┬ commander@2.9.0
  │ └── graceful-readlink@1.0.1
  ├── ejs@2.4.1
  ├── mime@1.3.4
  ├─┬ multiparty@4.1.2
  │ └─┬ fd-slicer@1.0.1
  │   └── pend@1.2.0
  ├─┬ mysql2@1.0.0-rc.1
  │ ├── bn.js@4.10.3
  │ ├─┬ cardinal@0.5.0
  │ │ ├── ansicolors@0.2.1
  │ │ └─┬ redeyed@0.5.0
  │ │   └── esprima-fb@12001.1.0-dev-harmony-fb
  │ ├── double-ended-queue@2.1.0-0
  │ ├─┬ named-placeholders@1.1.1
  │ │ └── lru-cache@2.5.0
  │ ├─┬ readable-stream@2.0.5
  │ │ ├── core-util-is@1.0.2
  │ │ ├── inherits@2.0.1
  │ │ ├── isarray@0.0.1
  │ │ ├── process-nextick-args@1.0.7
  │ │ ├── string_decoder@0.10.31
  │ │ └── util-deprecate@1.0.2
  │ └── seq-queue@0.0.5
  ├── thinkit@4.8.0
  └── validator@4.2.0

npm verb exit [ 0, true ]
npm info ok`

## ENV

Platform:

Node.js Version:

v5.10.1

ThinkJS Version:

thinkjs@2.2.3

npm Version:
3.8.6

电脑:
mac

## 遇到的问题:

`thinkjs -V`
`zsh: command not found: thinkjs`

**Comment by welefen** [comment]
是你的环境变量问题

**Comment by AaronLeong** [comment]
怎么解决
