### ISSUE TITLE
关于 service 调用其他 service 时，不能用this

### ISSUE THREAD

**Issue by llqgit** [75team/thinkjs#358]
### 关于 service 调用其他 service 时，不能用this
------------------------------------
比如我有一个发短信的service： msg_service
当我想用，user_service 调用他的时候，我需要这么写
``` javascript
think.service('msg_serivce', 'user');
```
而不能：
``` javascript
this.service('msg_service');
```
### 另一个问题：比如我在一个service 里，多个方法都需要调用 发短信的服务 msg_service
------------------------------------
现在有两种方式：
#### 1.每个方法里都写一句 
```  javascript
let msg_service = new (think.service('msg_serivce', 'user'))();
```
#### 2.在 **init(...args)** 的初始化方法里，写一句 
``` javascript
this.msg_service = new (think.service('msg_serivce', 'user'))();
``` 
然后在每个方法里调用 
``` javascript
this.msg_service.functions()；
```

**请问，有没有更好的解决方案，或者能够优化这部分的架构，因为这样操作觉得不舒服。。**

## ENV

Platform: mac

Node.js Version: 5.10

ThinkJS Version: 2.2

**Comment by welefen** [comment]
恩，后续版本里考虑添加 `this.service` 方法
