### ISSUE TITLE
nginx websocket问题

### ISSUE THREAD

**Issue by rindybo** [75team/thinkjs#359]
## DESC
我在本地开发socket.io没有问题 但是部署的服务就连接不上 报的400
服务端口是18081,也把这个端口开放出来 都是不行

io('http:// test.zhubohezi.com‘);
io('http:// test.zhubohezi.com:18081‘);
io('http:// ip‘);
io('http://ip:18081‘);

这几种方式全部试过 都是连接不上，请问这个配置有问题吗

`http {

	server {
	    listen 80;
	    server_name test.zhubohezi.com;
	    root /home/zhubohezi/test.zhubohezi.com;
	    set $node_port 18081;

	    index index.js index.html index.htm;
	    if ( -f $request_filename/index.html ){
		rewrite (.*) $1/index.html break;
	    }
	    if ( !-f $request_filename ){
		rewrite (.*) /index.js;
	    }
	    location = /index.js {

		proxy_http_version 1.1;
		proxy_set_header Connection "";
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header Host $http_host;
		proxy_set_header X-NginX-Proxy true;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_pass http://127.0.0.1:$node_port$request_uri;
		proxy_redirect off;
	    }
	    
	    location = /development.js {
		deny all;
	    }

	    location = /testing.js {
		deny all;
	    }

	    location = /production.js {
		deny all;
	    }

	    location ~ /static/ {
		etag         on;
		expires      max;
	    }
	}

	
}`

## ENV

Platform:
centos7
Node.js Version:
4.26
ThinkJS Version:
2.23

**Comment by welefen** [comment]
你的 nginx 是什么版本的呢？

**Comment by welefen** [comment]
还有线上 18081 这个端口是不是被限制了

**Comment by rindybo** [comment]
nginx的版本是1.10.X
已确认是我在 config.js 里面设置了timeout:0所导致的 ，不过一定要在服务器吧18081的端口对外开放
用80端口不行
