### ISSUE TITLE
websocket session操作

### ISSUE THREAD

**Issue by rindybo** [75team/thinkjs#362]
## DESC
请问如何在websocket的action中设置session登录状态，文档有提到在open action中可以获取验证session,但是我测试过在index设置好sesion,open中的session一直时undefined,获取的key(cookie)与在浏览器生成的不一致。
现在的需求是checklogin(websocket)，验证通过就设置session登录状态，不知道如何操作

## ENV

Platform:
windows8&centos7
Node.js Version:
4.2
ThinkJS Version:
2.2.x

**Comment by welefen** [comment]
你用的 websocket 类型是什么呢？ socket.io 还是 SockJS。

**Comment by rindybo** [comment]
socket.io

**Comment by welefen** [comment]
socket.io open 的时候可以拿到是否是登录状态的

**Comment by cnzin** [comment]
@welefen socket.io 类型, ws事件类型映射的方法里, 使用 `redis` `file` 等 session 读写都无效.

**Comment by chenyuncai** [comment]
连接socket时不要写127.0.0.1的host，需要写localhost,线上时候就是域名。浏览器出于安全角度，对ip地址的socket连接请求不发送cookie
