### ISSUE TITLE
art-template模板引擎适配器。

### ISSUE THREAD

**Issue by 1021683053** [75team/thinkjs#368]
## DESC
链接：https://github.com/1021683053/think-template-art
能不能把适配器放到官网上面
## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by qgy18** [comment]
你可以直接 fork 官网项目，改完发个 pr 就好了：
https://github.com/75team/www.thinkjs.org

**Comment by welefen** [comment]
已更新到官网
