### ISSUE TITLE
mysql 报错误This socket has  been ended by the other party

### ISSUE THREAD

**Issue by xbl** [75team/thinkjs#371]
## DESC
数据库连接池配置的10，Centos和windows都会报这个错，不太理解是什么错误，没有做什么复杂操作，只是做了单表查询和插入

## ENV

Platform: Centos, windows 

Node.js Version:v6.2.1

ThinkJS Version:v2.2.4

**Comment by qq312384485** [comment]
我也是一样的问题 同问

**Comment by welefen** [comment]
数据库配置的超时时间是多长呢？

**Comment by xbl** [comment]
没有配置，是默认的
