### ISSUE TITLE
关于mongodb无法使用$push和$pull问题。

### ISSUE THREAD

**Issue by hao3304** [75team/thinkjs#374]
## DESC
我反复测试了下，问题出现在schema里面的update字段定义的时候我增加了 update: true
` update:{
            default:function (){
                return new Date().getTime();
            },
            update: true
        }
`
然后每次使用$pull和$push 就会报错：
MongoError: The dollar ($) prefixed field '$push' in '$push' is not valid for storage

然后去掉update就好了，所以我只能手动去实现这个功能。

## ENV

Platform:OS X 

Node.js Version:4.2.5

ThinkJS Version:2.2

**Comment by welefen** [comment]
多谢反馈

**Comment by welefen** [comment]
这个是因为默认值导致的，因为设置了更新的时候自动加上 `update` 字段

**Comment by welefen** [comment]
等同于 issue  https://github.com/75team/thinkjs/issues/347
