### ISSUE TITLE
提出一些个人建议

### ISSUE THREAD

**Issue by jiuwoniu99** [75team/thinkjs#375]
## DESC
建议使用 --es 命令创建thinkjs项目时 /src目录下的js文件都改用.es6的后缀
很多编辑器已经支持.es6文件的查看和编辑
同时希望能添加一个配置，能在自动编译时对自定义扩展名的一个过滤 如.jsx 或是自定义扩展名
目前有很多前端项目支持也es6，但是需要对应配套的node编译环境。
希望thinkjs同时也能对/www/statc也能实现es6预编译
## ENV

Platform: OS X

Node.js Version: 6.2.1

ThinkJS Version: 2.2.4

**Comment by welefen** [comment]
多谢建议

第一个建议：为什么要改扩展名呢？

第二个建议已经在规划中了，会在 2.3.0 这个大版本中支持

**Comment by jiuwoniu99** [comment]
改扩展名的原因是我在模块中有一个assets目录，该目录下存放web端用的js，修改hook中的resource配置定位到每个模块的assets目录 ，我不想assets目录下的js一起被编译

**Comment by welefen** [comment]
OK，下个大版本会综合考虑这些事情
