### ISSUE TITLE
如何配置可以让参数可以有可无？

### ISSUE THREAD

**Issue by FuDengrong** [75team/thinkjs#378]
### control层
~~~javascript
let params = this.post();
await model.where(params).select()
~~~
### logic层
~~~javascript
this.allowMethods = 'post';
let rules = {
      name: 'required|string'
}
~~~

如题所示，因前台某些参数可有可无，有的话就要在logic里面做参数校验；
这时如果前台没有传参数,因为logic层做了参数校验的，在control层就变成了
~~~javascript
await model.where({name: ""}).select()
~~~
这时在后台就找不到数据

我想请问一下：如何做才能保证在有校验的情况下，如果没有传参数，where语句里面也是空的？谢谢！

**Comment by welefen** [comment]
去掉 required

**Comment by FuDengrong** [comment]
可是去掉之后还是会校验这个参数，并赋值为空字符串

**Comment by welefen** [comment]
已经修复， 见： https://github.com/75team/thinkjs/commit/298d44e98831ad20f6afaa157aa742171b145982

**Comment by FuDengrong** [comment]
@welefen ok, thank you!
