### ISSUE TITLE
更改项目默认模块后访问index controller的问题

### ISSUE THREAD

**Issue by XyzalZhang** [75team/thinkjs#381]
## DESC
创建项目后,默认模块home,
访问localhost:8088/
/home/controller/index/indexAction响应正常,
访问localhost:8088/text
/home/controller/index/textAction响应正常,
更改默认模块为manager,访问localhost:8088/
/manager/controller/index/indexAction响应正常,
访问localhost:8088/text
/manager/controller/index/textAction无法响应
必须访问localhost:8088/manager/index/text才能正确响应,

就是感觉配置了默认模块后只有访问默认模块的indexAction正常,其他action必须module/conroller/action全路径才能访问
是我没配置好么?
## ENV

Platform:

Node.js Version:
v6.2.1

ThinkJS Version:
v2.2

**Comment by welefen** [comment]
默认 localhost:8088/text 不会命中到 /home/controller/index/textAction，是配置了自定义路由么？

如果配置了自定义路由，更改默认模块后，自定义路由里也要对应改下

**Comment by XyzalZhang** [comment]
没有配置route_on,也没有route.js
