### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by minerchow** [75team/thinkjs#382]
## DESC
![image](https://cloud.githubusercontent.com/assets/3675138/16537267/cc30d412-4030-11e6-87ea-6a956742a27a.png)

## ENV

Platform:

Node.js Version:4.4.5

ThinkJS Version:2.2.5

**Comment by welefen** [comment]
有安装依赖么？

**Comment by minerchow** [comment]
恩, npm install了

**Comment by welefen** [comment]
这个问题有解决么？  不行的话把依赖删了重新装下试试

**Comment by minerchow** [comment]
木有，thinkjs都重装过了

**Comment by minerchow** [comment]
另外一台电脑上能跑起来，有点奇怪
