### ISSUE TITLE
建议NPM包将src一起发布

### ISSUE THREAD

**Issue by zl810881283** [75team/thinkjs#384]
使用之前thinkjs版本都可以直接定位到框架源码，更新到2.2.5后发现src文件没有了，只有到github上查看源码，还是有点麻烦的。

**Comment by welefen** [comment]
恩，下个版本加回来

**Comment by welefen** [comment]
Fix by https://github.com/75team/thinkjs/commit/cb5a7386c6d3a11501d0f5b9b69885d0c2366e2b
