### ISSUE TITLE
file logic 校验图片扩展名（后缀）

### ISSUE THREAD

**Issue by llqgit** [75team/thinkjs#387]
## DESC

file 的校验 logic 有没有能提供文件类型的校验规则？
类似：
``` javascript
this.rules = {
  image: 'file:png,jpg|required'
}
```

## ENV

Platform: Mac

Node.js Version: 6.2.0

ThinkJS Version: 2.2.3

**Comment by welefen** [comment]
```
this.rules = {
   image: 'required|image'
}
```

**Comment by welefen** [comment]
支持的图片格式为： jpeg, jpg, png, bmp, gif, svg

**Comment by llqgit** [comment]
有没有限制大小size功能

**Comment by welefen** [comment]
现在没有，你可以在项目里扩展一个规则就可以了

**Comment by welefen** [comment]
这个规则是可以扩展的，具体见： https://thinkjs.org/zh-cn/doc/2.2/logic.html#toc-c4f

**Comment by llqgit** [comment]
好的，多谢

**Comment by llqgit** [comment]
又出现了一个关于上传图片的logic验证问题，就像你说的
我用了：
```
this.rules = {
   photo: 'required|image'
}
```
结果是：
```
{
  "errno": 1001,
  "errmsg": {
    "photo": "photo can not be blank"
  }
}
```
我改用：
```
this.rules = {
   photo: 'required|file'
}
```
结果是正确的。。
我的版本是
>thinkjs v2.2.1
nodejs v6.2.0

**Comment by welefen** [comment]
是的，之前写错了， `file` 表示这个值从 http.file 对象里获取，默认是从 post 里获取的。可以配置成这样

`required|file|image`

**Comment by llqgit** [comment]
嗯嗯，ok👌
