### ISSUE TITLE
操作mysql时貌似有冗余

### ISSUE THREAD

**Issue by zhangchen91** [75team/thinkjs#389]
## DESC

对model进行任何操作都会先执行一个SHOW COLUMNS的SQL：

比如：

let user = this.model("user");
let count1 = await user.count();
let count2 = await user.count();
let count3 = await user.count();

日志里会有
SHOW COLUMNS FROM `think_user` 24ms
SELECT COUNT(id) AS think_count FROM `think_user` LIMIT 1 21ms
SHOW COLUMNS FROM `think_user` 26ms
SELECT COUNT(id) AS think_count FROM `think_user` LIMIT 1 22ms
SHOW COLUMNS FROM `think_user` 22ms
SELECT COUNT(id) AS think_count FROM `think_user` LIMIT 1 21ms

## ENV

Platform: mac 

Node.js Version: v6.2.1

ThinkJS Version: v2.2.5

**Comment by welefen** [comment]
这个只在开发环境下出现，主要是实时更新数据表的字段信息
