### ISSUE TITLE
rate limit 支持

### ISSUE THREAD

**Issue by airyland** [75team/thinkjs#393]
是否会考虑内置rate limit的支持？可以方便针对ip，id，或者token等进行请求频率限制。

**Comment by welefen** [comment]
可以通过中间件来完成，如： https://github.com/thinkjs-team/think-ip-filter

**Comment by welefen** [comment]
如果这个中间件不能满足你的需求的话，你可以照着这个实现个

**Comment by airyland** [comment]
ip中间件主要用来实现白名单黑名单，当前我确实是写了个middleware来实现，但是感觉ratelimit算web应用的基本功能，如果内置支持会比较合适。

**Comment by welefen** [comment]
ratelimit 如果功能很全面的话需要结合第三方服务，如：Redis。

所以默认情况下只能提供一个基础的，项目中可以根据需要进行扩展开发。
