### ISSUE TITLE
请问如何配置view的adapter,比如说我要配置swig的varControls

### ISSUE THREAD

**Issue by XyzalZhang** [75team/thinkjs#396]
## DESC
请问如何配置view的adapter,比如说我要配置swig的varControls,
我是要重写swig的adapter还是直接在view.config里面配置

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
通过配置即可

```js
export default {
   type: 'swig',
   adapter: {
     varControls: ['{{', '}}'],
     ...
   }
}
```
