### ISSUE TITLE
mysql开启连接池后事务操作会被中断

### ISSUE THREAD

**Issue by qq312384485** [75team/thinkjs#401]
## DESC
配置中设置 connectionLimit: 2, 运行中发现有大量事务执行超时把表给锁住了  排查发现把 connectionLimit设置成1之后问题就解决了  猜测是多连接是有可能会在事务中间切换到另一个连接执行剩下的sql导致事务出错

## ENV

Platform:2.2.5

Node.js Version:

ThinkJS Version:2.2.5

**Comment by welefen** [comment]
开启事务后不能使用连接池，node-mysql2 模块会分配到不同的连接上去导致报错。
这个需要 node-mysql2 支持，暂时不能解决

**Comment by qq312384485** [comment]
好的
