### ISSUE TITLE
form提交 checkbox 使用this.http.getPayload()获取值错误

### ISSUE THREAD

**Issue by Jerret321** [75team/thinkjs#403]
## DESC
checkbox form提交通过this.http.getPayload()解析后获取的数据：
true是 on
false是undefined

具体表现如下：
```bash
[2016-07-24 22:34:43] [SQL] SHOW COLUMNS FROM `app` 2ms
name=juju&os=1&description=&logo=&is_force_update=on&uid=5
```

## ENV

Platform: OSX

Node.js Version: 5.8.0

ThinkJS Version:2.2.5

**Comment by qgy18** [comment]
这个符合预期啊，checkbox 如果不设置 value 属性，在选中时就是会发送 `on`，不选中时不会发送这个字段。

**Comment by Jerret321** [comment]
恩，也能接受啊 就是感觉挺奇怪的。
