### ISSUE TITLE
2.2.6版本下，加载js静态资源,返回数据不正常

### ISSUE THREAD

**Issue by shekobe** [75team/thinkjs#405]
## DESC

会返回页面的数据，不是返回js文件的内容

## ENV

Platform:win32

Node.js Version:3.0.0

ThinkJS Version:2.2.6

**Comment by welefen** [comment]
我这边测试没发现这个问题，你的 JS 资源具体路径是什么呢？ 直接浏览器访问这个 JS 地址看下返回内容

**Comment by noonhorse** [comment]
确实返回有问题，在windows 下
错误如下
controller `static` not found. url is `/static/js/common/header.js`.</pre>

**Comment by shekobe** [comment]
js路径：/static/js/js.js    在浏览器打开也是返回页面代码  ，我换回2.2.5就返回正常了，我是用thinkjs命令建的项目  thinkjs new thinkjs_demo  ，然后把package.json  改到 "thinkjs": "2.2.6"  再 npm install 访问js不正常，然后删除node_modules ,   改到 "thinkjs": "2.2.5" 再安装包，访问js 就没问题

**Comment by welefen** [comment]
OK，确认是 windows 下的问题。。。

**Comment by welefen** [comment]
已经修复，发布了 2.2.7 版本
