### ISSUE TITLE
使用nunjucks的时候 在common中有app的文件 引入失败

### ISSUE THREAD

**Issue by Jerret321** [75team/thinkjs#407]
## DESC
![image](https://cloud.githubusercontent.com/assets/2155745/17268717/8ce9e3fc-5665-11e6-9641-9a9376ef8b50.png)

换成其他的名称就好了

## ENV

Platform: centOS 6.5

Node.js Version: 5.0.0

ThinkJS Version: 2.2.x

**Comment by Jerret321** [comment]
没有报错信息呢， development下 显示效果上是没有include文件。

**Comment by welefen** [comment]
把其他无关的代码都去除，确认下是不是名字导致的。理论上不应该出现这种情况的

**Comment by Jerret321** [comment]
我先把问题关闭了吧， 目前已经可以正常在线上运行了。 等测试后的结果，在反馈吧
