### ISSUE TITLE
model.buildSql方法的返回值为什么要加上括号呢

### ISSUE THREAD

**Issue by qq312384485** [75team/thinkjs#415]
## DESC
async buildSql(options){
    options = await this.parseOptions(options);
    return '( ' + this.db().buildSelectSql(options).trim() + ' )';
  }
我发现返回的sql语句被加上括号了,我这边的应用场景是通过buildSql获取sql语句然后拼接上 for update等api不支持的sql操作,加了括号就不方便处理了 这个括号是不是能去掉呢

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
已经支持第二个参数控制是否添加小扩展，默认添加。

可以通过 `buildSql(options, true)` 来控制不添加，将在 2.2.13 版本中支持。
