### ISSUE TITLE
mariadb where ("1=1") 报语法错误

### ISSUE THREAD

**Issue by xiaoyunchen** [75team/thinkjs#420]
## DESC
需要更新表中的所有数据，使用了如下方法：
await model.where("1=1").update({
			token:newtoken
		});

最后报错：
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE ( id = 1 )' at line 1

## ENV
linux mariadb

Platform:

Node.js Version:
6.2.2

ThinkJS Version:
2.2.8

**Comment by welefen** [comment]
你直接把生成的 SQL 拷贝执行也报错么？

**Comment by xiaoyunchen** [comment]
抱歉，问题定位到了，不是thinkjs问题，是我们的线上环境node包的问题，已经解决，感谢支持。
