### ISSUE TITLE
仍然mongo丢失连接

### ISSUE THREAD

**Issue by murongyuange** [75team/thinkjs#428]
## DESC
我升到了2.2.9,问题依旧存在.系统里,我放了2个mongo库,是不是这个引起的?

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by murongyuange** [comment]
补充:本模块下(存取session没有问题),跨模块的存取丢失连接

**Comment by welefen** [comment]
跨模块下是不同的 mongo 配置么？

**Comment by welefen** [comment]
如果是同一份配置 跟有没有跨模块应该没什么关系

**Comment by murongyuange** [comment]
好了,我把app删了,重新编译了,又把mongo的大部分数据删了,就好了.暂时没有发现具体原因
