### ISSUE TITLE
静态资源不存在，http的状态码为200，然后thinkjs就不在响应任何请求

### ISSUE THREAD

**Issue by zuoyanart** [75team/thinkjs#433]
## DESC

静态资源不存在的情况下，访问几次，thinkjs就不在响应任何请求了
## ENV

Platform: centos 6.8， 本地测试centos 7测试， 没有出现无响应的情况

Node.js Version: 4.5.0

ThinkJS Version: 2.2.9

**Comment by zuoyanart** [comment]
看了下nginx的配置文件，大致逻辑是如果文件不存在，则交给thinkjs来处理， 但是静态文件从根本上不需要thinkjs处理（seo的除外），有没有办法来处理？

**Comment by welefen** [comment]
你的 nginx 是如何配置的？

**Comment by zuoyanart** [comment]
`server {
    listen 80;
    server_name t.371sports.com;
    root /home/data/host/sportsWeb/www;
    set $node_port 3000;

    index index.js index.html index.htm;
    if ( -f $request_filename/index.html ){
        rewrite (.*) $1/index.html break;
    }
    if ( !-f $request_filename ){
        rewrite (.*) /index.js;
    }
    location = /index.js {
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://127.0.0.1:$node_port$request_uri;
        proxy_redirect off;
    }
    
    location = /development.js {
        deny all;
    }

    location = /testing.js {
        deny all;
    }

    location = /production.js {
        deny all;
    }

    location ~ /static/ {
        etag         on;
        expires      max;
    }
}   
`
按照文档走的

**Comment by zuoyanart** [comment]
`server {
    listen 80;
    server_name t.371sports.com;
    root /home/data/host/sportsWeb/www;
    set $node_port 3000;

    index index.js index.html index.htm;
    if ( -f $request_filename/index.html ){
        rewrite (.*) $1/index.html break;
    }
    if ( !-f $request_filename ){
        rewrite (.*) /index.js;
    }
    location / {
       if ( -f $request_filename/index.html ){
            rewrite (.*) $1/index.html break;
        }
        if ( !-f $request_filename ){
            rewrite (.*) /index.js;
        }
      }


    location = /index.js {
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://127.0.0.1:$node_port$request_uri;
        proxy_redirect off;
    }
    
    location = /development.js {
        deny all;
    }

    location = /testing.js {
        deny all;
    }

    location = /production.js {
        deny all;
    }

    location ~ /static/ {
        etag         on;
        expires      max;
    }
    location ~* .(gif|jpg|jpeg|png|swf|htm|html|txt|bmp|css|js)$ {
     proxy_pass http://www.baidu.com;
     break;
   }
}   `

貌似用location / 来处理文件不存在的情况，是可行的。就是不知道为啥，thinkjs 响应几个不存在的图片文件就任何请求都不响应了，好奇怪的。也不知道怎么查

**Comment by welefen** [comment]
用开发模式启动，然后看看请求日志

**Comment by zuoyanart** [comment]
看了，没有日志，停止响应后，控制台就看不到任何新日志了

**Comment by welefen** [comment]
直接 npm start 启动服务也看到日志？

**Comment by welefen** [comment]
那没到 Node 吧，你可以通过端口访问看看

**Comment by zuoyanart** [comment]
curl http://127.0.0.1:3000  这样吗？，这样也访问不到。
如果是没到NODE的话，我应该怎么做呢？源码编译重新安装下NODE？

**Comment by welefen** [comment]
你重建个项目，或者在其他机器上试下呢

**Comment by zuoyanart** [comment]
可能是系统的问题吧， 我先运行这，不让thinkjs处理静态文件好了

**Comment by zuoyanart** [comment]
我的问题解决了， 是我的路由写的不好，导致如果连接地址很长的话，cpu就飙到了100%。还得好好看正则啊
