### ISSUE TITLE
获取header自动转key为小写

### ISSUE THREAD

**Issue by simman** [75team/thinkjs#438]
## DESC

根据规范 header 里面的 key 是大小写不敏感的， request 传上来的时候都已经转为小写了，那么获取的时候把 name 转为小写也是应该的吧？

https://github.com/75team/thinkjs/blob/master/src/core/http.js#L382

## ENV

Platform:  Mac OSX

Node.js Version: v5.6.0

ThinkJS Version: v2.2.9

**Comment by welefen** [comment]
你帮忙改下 然后发个 pull requst？
