### ISSUE TITLE
一个app里面如何操作多个数据库CURD

### ISSUE THREAD

**Issue by Jerret321** [75team/thinkjs#441]
## DESC

有需求要对一个mongo，进行多库的CURD。

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
那就弄多个配置，操作的时候选用对应的配置使用就可以

**Comment by Jerret321** [comment]
在thinkjs 具体怎么做呢？  因为程序运行默认为连接默认的配置

**Comment by welefen** [comment]
db.js

```js
export default {
  type: 'mysql1',
  adapter: {
    mysql1: {
      type: 'mysql',
      host: '...'
    }
  }
}
```

let model = this.model('user', 'mysql1');

**Comment by Jerret321** [comment]
soga 多谢了。
