### ISSUE TITLE
form提交 getPayload 传输 数组 会截断数据

### ISSUE THREAD

**Issue by Jerret321** [75team/thinkjs#443]
## DESC
如这样的结构: 
[{"label_name":"姓名","placeholder":"请输入姓名","field_name":"name","value":""},{"label_name":"邮箱","placeholder":"请输入一个邮箱","field_name":"email","value":""}]

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by Jerret321** [comment]
已找到原因了

**Comment by welefen** [comment]
具体是什么问题导致的呢？

**Comment by Jerret321** [comment]
是我写错了。 不过还有个问题就是 空格老是自动转成 +++ `decodeURI`和`decodeURIComponent`是不会对空格做这种转换 具体你可以测试下。
