### ISSUE TITLE
afterSelect afterFind 在多请求下，导致 data 共享的问题

### ISSUE THREAD

**Issue by llqgit** [75team/thinkjs#445]
## DESC

我在调用查询数据库方法时，需要对返回数据进行二次开发，
比如：在图片的 URL 前添加服务器的 BASE_URL
eg:
```
/upload/img/abc.png
```
添加前缀后 BASE_URL ```http://abc.com```
```
http://abc.com/upload/img/abc.png
```

然而，比如我在同时多次调用查询接口的时候，会发现，data 被共享了。
而且在，服务器的生产模式，状况会更加复杂

结果是：
```
http://abc.com/http://abc.com/upload/img/abc.png
```
or
```
http://abc.comhttp://abc.com/http://abc.com/upload/img/abc.png
```
即，```data``` Some how被传递下去了。
搞的我有点懵B了，不知道是什么错误，求解救。。。。。。

## ENV

Platform: mac and centos

Node.js Version: 6.3.0

ThinkJS Version: 2.10.0

**Comment by qgy18** [comment]
不要直接修改返回的数据，拷贝一份出来再改，例如：

```js
let newData = think.extend({}, data);
```

**Comment by llqgit** [comment]
@qgy18 好，我试试
