### ISSUE TITLE
Bad example on homepage

### ISSUE THREAD

**Issue by tracker1** [75team/thinkjs#446]
The example on the homepage is using md5... the example should probably be using an hmac based hashing, or pbkdf2...

**Comment by llqgit** [comment]
Un, I think it's easy to understand for somebody new.
Exactly, when someone like me do not know hmac.... :P

**Comment by welefen** [comment]
om, It just an example

**Comment by tracker1** [comment]
I know it's just an example... but as an example, and as a framework... the `think.md5` method itself should either be changed to `sha384hmac` or similar, I don't know if the framework has such a beast...

Alternatively, a comment saying, `// NOTE: you should use custom salt, and a stronger hash than MD5.`

**Comment by tracker1** [comment]
```
let result = await this.model('user').where({name: data.name }).find();
// either the user is invalid, or the password doesn't match
if (think.isEmpty(result) || !checkPassword(result, data.pwd)) {
  // fail the event with a random wait up to 1 second, overcome timing attacks
  return setTimeout(() => this.fail('login fail'), Math.random() * 1000);
}
```

If you don't define the checkPassword... also, fail method should probably implement the random delay, if it doesn't already.

**Comment by welefen** [comment]
Thx a lot, it updated.
