### ISSUE TITLE
mongodb sql log 不打印

### ISSUE THREAD

**Issue by llqgit** [75team/thinkjs#448]
## DESC

我就想弱弱的问一句，为什么mongodb 的 sql log 不打印

```
type: 'mongo',
log_sql: true,
```

## ENV

Platform: macOS

Node.js Version: 6.3.0

ThinkJS Version: 2.2.10

**Comment by llqgit** [comment]
我想在 mongodb 的一个表的所有字段搜索包含 '100' 这个值的所有列，
我用 $regex
但是不能在所有字段检索，
我只能用 $or 来把所有的 title 复制一遍 regex

有没有好办法？
ps：mongo 不打印查询 log

**Comment by welefen** [comment]
mongo 并不会生成 SQL 语句，所以没法打印

**Comment by llqgit** [comment]
为在模糊查找的时候，需要进行按时间区间分页查询：
```
let start_time = new Date(0);
let end_time = new Date();
return this.where({
      date: {$gt: start_time, $lt: end_time},
      // $regex: search
      $or: [
        { order_id: { $regex: reg } },
        { user_name: { $regex: reg } }
      ]
    }).order({'CH_date': -1}).page(page_no, nums_per_page).countSelect();
```
大体的代码是这个意思的，运行起来没有语法错误。
在```mongo```中运行，查询结果正常，而在 **think** 中的查询，返回为空

我怀疑，think 将 start_time 转成了字符串。只是怀疑，因为没有任何的log，
不知道 think 是用什么最终参数，进行的查询。

think 中 注掉
```
date: {$gt: start_time, $lt: end_time},
```
这句，查询正常，求解 (TT)
@welefen

**Comment by xiaoyunchen** [comment]
mongo 不打印SQL  请问有什么好的调试方式吗？经常报错都不知道问题在哪？
