### ISSUE TITLE
请问docker中运行pm2 start pm2.json --no-daemon报Error: PREVENT_NEXT_PROCESS，怎么解决？

### ISSUE THREAD

**Issue by dingyiming** [75team/thinkjs#453]
## DESC

- 报错截图
![image](https://cloud.githubusercontent.com/assets/12537013/18752193/38ad994e-8114-11e6-838c-dca0503fd747.png)

- dockerfile 

```
# 获取node镜像
FROM node

RUN npm i -g pm2

ADD . /home/watchdog-api

WORKDIR /home/watchdog-api

RUN npm install

RUN npm run build

# CMD sleep 100000000000

ENTRYPOINT pm2 --no-daemon start pm2.json
```

- 官网有类似解释，但，不知道如何修改 ，有这个报错就无法访问了
![image](https://cloud.githubusercontent.com/assets/12537013/18752325/a009ffe2-8114-11e6-9235-7e8393027a76.png)

## ENV

Platform: dockerHub node镜像  https://hub.docker.com/_/node/  用daocloud构建后部署

Node.js Version: v6.6

ThinkJS Version: 2.2.x

**Comment by dingyiming** [comment]
哦，在Daocloud工程师帮助下解决了，还是得用deamon方式运行，不过这样就看不到log,然后虽然，docker 1号进程不能以daemon的方式来跑，因为daemonize的时候会杀掉原进程起一个孤儿进程。。。，但总算能跑了。。。

- 如下dockerfile可用

```
# 获取node镜像
FROM node

RUN npm i -g pm2

ADD . /home/watchdog-api

WORKDIR /home/watchdog-api

RUN npm install

RUN npm run build

# CMD sleep 100000000000

ENTRYPOINT pm2 start pm2.json; sleep 100000
```

**Comment by flftfqwxf** [comment]
我使用pm2 启动时，如果 使用

> "exec_mode": "cluster",
>  "instances": 2,

也会有此问题，请问是怎么解决的？

**Comment by welefen** [comment]
https://github.com/thinkjs/thinkjs/issues/507
