### ISSUE TITLE
运行 node www/production 找不到静态资源

### ISSUE THREAD

**Issue by flftfqwxf** [75team/thinkjs#458]
运行node www/development时一切正常，运行node www/production 找不到静态资源，
所有静态资源访问都是404.
页面可以访问，env/production.js 未做任何修改，也并没有报错，并且尝试在env/production.js 中修改port也并未不生效，求解

**Comment by welefen** [comment]
production 下默认关闭了静态资源的处理，该环境下静态资源处理建议用 nginx 来做
