### ISSUE TITLE
wrong content-type in www folder

### ISSUE THREAD

**Issue by Jerret321** [75team/thinkjs#464]
## DESC
当在www建立新的文件夹下 放css js等资源是，引用资源 content-type解析为 text/html

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
是什么环境呢？ 开发环境测试未发现该问题

**Comment by Jerret321** [comment]
目录结构如下：
```
www
---cc
     ---aa.css
aa.css
```
aa.css是正确的，套层结构就错误了。

**Comment by welefen** [comment]
![](http://p5.qhimg.com/t01d58b1d83445a38c6.jpg)

试了下也没问题的

**Comment by Jerret321** [comment]
额 不放在 static里啊。

**Comment by welefen** [comment]
不放在 static 里，不改静态资源规则的话，ThinkJS 是不处理这些静态资源的

**Comment by Jerret321** [comment]
ok 了解了

**Comment by welefen** [comment]
确认下，这个请求经过 ThinkJS 处理了么？

**Comment by Jerret321** [comment]
![image](https://cloud.githubusercontent.com/assets/2155745/19354657/19c76956-919a-11e6-87a6-79ed498c1d02.png)

**Comment by welefen** [comment]
这个是被当成页面处理的，因为没有命中静态资源的规则啊。

你可以看返回内容并不是 a.css 的文件内容。
