### ISSUE TITLE
[FEATURE] use uWebSocket for socket.io

### ISSUE THREAD

**Issue by im-kulikov** [75team/thinkjs#466]
## DESC

Highly scalable WebSocket server & client library:
https://github.com/uWebSockets/uWebSockets

`10-300x faster than ws` 

all need to do:
```js
var io = require('socket.io')(80);
io.engine.ws = new (require('uws').Server)({
    noServer: true,
    perMessageDeflate: false
});
```

i can make PR if need..

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
You can make think-uwebsockets package to support uWebsockets

**Comment by im-kulikov** [comment]
@welefen I need to do it as part of the core adapter or a separate repository?

**Comment by welefen** [comment]
Separate repository, like https://github.com/thinkjs-team/think-template-handlebars

**Comment by im-kulikov** [comment]
👍  thnx, do it in few days

**Comment by im-kulikov** [comment]
https://github.com/im-kulikov/think-socket-uws released

it backward compatible with adapter/websocket/socket.io.js

code coverage greater than 95%.

**Comment by welefen** [comment]
Thx, it already add to https://thinkjs.org/en/plugin.html

**Comment by im-kulikov** [comment]
oh, it's cool))
