### ISSUE TITLE
thinkjs new demo 创建的项目没有admin和home两个模块

### ISSUE THREAD

**Issue by zhaoweijing2003** [75team/thinkjs#467]
## DESC

我使用thinkjs v2.2.12 然后使用thinkjs new demo 命令创建demo项目
可是创建的项目目录没有admin和home两个模块
是如下的文件列表：

 create : demo
 create : demo\package.json
 create : demo\.thinkjsrc
 create : demo\nginx.conf
 create : demo\pm2.json
 create : demo\.gitignore
 create : demo\README.md
 create : demo\www
 create : demo\www\development.js
 create : demo\www\production.js
 create : demo\www\testing.js
 create : demo\www\README.md
 create : demo\www\static
 create : demo\www\static\js
 create : demo\www\static\css
 create : demo\www\static\img
 create : demo\src
 create : demo\src\bootstrap
 create : demo\src\bootstrap\middleware.js
 create : demo\src\bootstrap\global.js
 create : demo\src\config
 create : demo\src\config\config.js
 create : demo\src\config\view.js
 create : demo\src\config\db.js
 create : demo\src\config\hook.js
 create : demo\src\config\session.js
 create : demo\src\config\error.js
 create : demo\src\config\env
 create : demo\src\config\env\development.js
 create : demo\src\config\env\testing.js
 create : demo\src\config\env\production.js
 create : demo\src\config\locale
 create : demo\src\config\locale\en.js
 create : demo\src\controller
 create : demo\src\controller\error.js
 create : demo\view
 create : demo\view\error_400.html
 create : demo\view\error_403.html
 create : demo\view\error_404.html
 create : demo\view\error_500.html
 create : demo\view\error_503.html
 create : demo\src\controller\base.js
 create : demo\src\controller\index.js
 create : demo\src\logic
 create : demo\src\logic\index.js
 create : demo\src\model
 create : demo\src\model\index.js
 create : demo\view\index_index.html

## ENV

Platform: windows 7 x64
Node.js Version: 6.6.0
ThinkJS Version: 2.2.12

**Comment by welefen** [comment]
现在默认创建的项目为单模块结构，如果想用多模块结构的话可以加上 --mode=module 参数

**Comment by zhaoweijing2003** [comment]
@welefen 正解，谢谢！thinkjs太棒了，写的。绝对是一个改变世界的框架，希望奇舞团能够出更多的视频教程来帮助学习者快速上手
