### ISSUE TITLE
分页查询时，参数名称支持可配置

### ISSUE THREAD

**Issue by yangBin666** [75team/thinkjs#477]
## DESC

目前支持分页查询，但是返回的结果是类似
`{
count: 546,
totalPages: 28,
numsPerPage: 20,
currentPage: 1,
data: []
}`
这种格式，是否可以支持通过配置文件的形式更改对应的这些属性的名称？

ps：目前版本下，我是通过继承model和rest，分别修改对应的countSelect方法来实现的

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
为啥要修改属性的名称呢？

**Comment by yangBin666** [comment]
主要是项目上只使用了thinkjs的后端功能，现有的前端使用的参数名称与thinkjs的返回的参数不一致。
ps：有类似angularjs+thinkjs的实现案例吗？

**Comment by hodgevk** [comment]
我觉得能修改属性名称是有必要的，像我们前端分页字段在各个子系统中都有不同的，尤其是跨大版本的时候

**Comment by welefen** [comment]
那可以寫個簡單的字段轉換函數就可以了。
