### ISSUE TITLE
更新最新thinkjs版本后，编译TypeScript报错

### ISSUE THREAD

**Issue by hodgevk** [75team/thinkjs#479]
## DESC
更新最新thinkjs版本后，编译typescript报错：
> [Error] TypeError: Cannot read property 'getLineAndCharacterOfPosition' of undefined

## ENV

Platform:windows 7

Node.js Version:6.3.1

ThinkJS Version:2.2.13

**Comment by welefen** [comment]
这是因为 babel 升级导致的。

将 package.json 里 babel-core 的依赖改为 `"babel-core": "^6.7.7"`，然后重新安装下依赖。

**Comment by hodgevk** [comment]
修改了package.json里的babel-core为^6.7.7，更新依赖了还是不行。

**Comment by welefen** [comment]
那看下 node_modules 里的 babel-core 版本是 6.7.7 么？

**Comment by smjhang** [comment]
新裝的 2.2.13 建新項目有一樣的問題，
thinkjs new demo --ts
cd demo
npm install
npm start
會報 ts 編譯錯誤
查看  node_modules/babel-core/package.json 的 "version": "6.17.0"

**Comment by hodgevk** [comment]
我直接指定babel-core版本为6.7.7，node_modules里的babel-core版本为6.7.7，一样报错

**Comment by hodgevk** [comment]
我直接指定babel-core版本为6.7.7，node_modules里的babel-core版本为6.7.7，一样报错

**Comment by welefen** [comment]
將 package.json 裏的 typescript 改為 2.0.3，然後重新安裝下依賴。

**Comment by hodgevk** [comment]
ok了，原来是使用了beta版了吧。

**Comment by hodgevk** [comment]
我还是用回es6版本吧，建议直接废掉ts版本，等es6完善了再捣鼓吧

**Comment by welefen** [comment]
@hodgevk 恩，之前必須依賴的功能只在 beta 版本裏纔有，現在 TypeScript 把有些接口改了導致報錯了。
