### ISSUE TITLE
thinkjs2.2.13数据库操作的两个bug，关于addMany和countSelect

### ISSUE THREAD

**Issue by floydcash** [75team/thinkjs#484]
## DESC

1、在model中，使用this.page(1,20).countSelect()；实际上，最终生成的sql语句是limit(0,10)；而this.page(2,20).countSelect()，生成的sql又是正确的limit(1,20)；

2、在model中调用 this.addMany(list)，而list是一个数组，数组只有一个对象，返回的id列表，居然是[0]，然而数据是成功塞进去数据库了，我看2.2.12版本修复了add的问题，addMany这个貌似有问题~~
## ENV

Platform:linux centos7

Node.js Version:4.5

ThinkJS Version: 2.2.13

**Comment by welefen** [comment]
page(1, 20) 和 page(2, 20) 生成的 SQL 如下，没发现你说的问题。
`[2016-11-02 15:43:53] [SQL] SELECT * FROM `aaa` LIMIT 20,20 1ms`
`[2016-11-02 15:44:38] [SQL] SELECT * FROM `aaa` LIMIT 0,20 0ms`

addMany 返回值问题在 https://github.com/75team/thinkjs/commit/0a08cff83ff947480d9021b67b7b05a57594375d 中修复了。
