### ISSUE TITLE
新手来报错

### ISSUE THREAD

**Issue by saopang** [75team/thinkjs#485]
## ENV

Platform:

```
[root@localhost tk]# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
[root@localhost tk]# cat /proc/version
Linux version 3.10.0-327.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Thu Nov 19 22:10:57 UTC 2015
```

Node.js Version: 6.9.1
NPM Version: 3.10.8
pm2 Version:2.0.18
ThinkJS Version: v2.2.13
## 错误信息

只修改了pm2.json里面的cwd为项目根路径
npm install之后的截图：
![image](https://cloud.githubusercontent.com/assets/11707936/19547552/5e4dfa82-96cb-11e6-842d-dafe667713df.png)
访问首页的截图：
![image](https://cloud.githubusercontent.com/assets/11707936/19547539/48abb11a-96cb-11e6-9069-8a195da225b3.png)

**Comment by welefen** [comment]
你的代码具体是怎么写的呢？应该是有 promise 没有 return 导致的，不过这个不影响程序的执行。
