### ISSUE TITLE
关系模型rModel配置无效

### ISSUE THREAD

**Issue by eurekao** [75team/thinkjs#486]
## DESC

关联关系模型名rModel只在查询时生效，修改编辑和删除时无效。需要修改`model\relation.js` 483行

```
let relationModel = this.getRelationModel(model);
```

为

```
let relationModel;
let relationTableName = mapOpts.rModel;
if(relationTableName){
  relationModel = this.model(relationTableName);
}else{
  relationModel = this.getRelationModel(model);
}
```
## ENV

Platform:Windows10

Node.js Version: 4.4

ThinkJS Version:2.2.13

**Comment by welefen** [comment]
Fixed by https://github.com/75team/thinkjs/commit/6b2fac9fc78830dc59f9bc3c818d504bb16b35bd
