### ISSUE TITLE
this.success 如何将分页信息显示在第一层和errno、errmessage在同一层,让 data 只有一层？

### ISSUE THREAD

**Issue by dingyiming** [75team/thinkjs#494]
## DESC

如果用 this.success 输出结果，然后带上分页信息，data 就包了两层，但如果用 this.json 输出结果，就没了错误信息。。。有什么好办法能 直接把分页信息显示得和 errno errmessage 在同一级吗？ 

## ENV

Platform:  windows
Node.js Version:  v6.9.1

ThinkJS Version: 2.2.x

**Comment by welefen** [comment]
框架建议的方式是数据放在 data 里。
你可以在 base controller 里加个通用的方法来实现这个功能，其他地方调用这个方法就可以了。

**Comment by dingyiming** [comment]
哦哦，感谢，我目前感觉 数据反馈状态有点搞不清晰， errno 和 errmessage 是否适合用来处理 应用中的逻辑错误状态？ 比如一些操作错误

**Comment by dingyiming** [comment]
我现在 在 base controller 里加了方法 ，普通controller 可以调用，但是在 rest controller 里面调用不到，请问 rest controller 里面如何调用到 base  controller 中的 方法？还有就是可以放到 common 模块中供所有一起用吗？

**Comment by dingyiming** [comment]
我目前是使用  this.controller 获取 common 模块中 controller 然后进行调用的，可行
