### ISSUE TITLE
在同一个hook点prepend多个middleware，只会执行最后一个

### ISSUE THREAD

**Issue by philoles** [75team/thinkjs#495]
## DESC
在同一个hook点prepend多个middleware，只会执行最后一个

例如有middleware xxx1和xxx2
config/hook.js里面
   logic_before: ["prepend", "xxx1"],
  logic_before: ["prepend", "xxx2"],
 
middleware xxx1不会执行

## ENV

Platform:win10 docker

Node.js Version:6.5

ThinkJS Version:2.2.12

**Comment by qgy18** [comment]
```javascript
logic: ["prepend", "xxx1", "xxx2"],
```

写成这样就好了，不然 js 对象同名 key 会覆盖。

**Comment by philoles** [comment]
谢谢，突然觉着自己很2
