### ISSUE TITLE
请问用redis做cache时，如何设置失效时间？我用think.cache(name,value,timeout) 无效

### ISSUE THREAD

**Issue by dingyiming** [75team/thinkjs#496]
## DESC

![i9_py39ws7sokf6gano cw4](https://cloud.githubusercontent.com/assets/12537013/19842004/0b7bd2e8-9f4f-11e6-896e-662e3d3d0123.png)

 redis adapter 里有这个可以设置失效时间的方法，如何使用？ 是 通过cache吗 如 think.cache(name, value, timeout) ? 我这么做无效，我应该怎么做？
## ENV

Platform: windows

Node.js Version: v6.9.1

ThinkJS Version: 2.2.x

**Comment by llqgit** [comment]
```javascript
think.cache('key_name', undefined, {
    timeout:  100,
    type: 'redis'
});
```
```javascript
think.cache('key_name', null);
```

**Comment by llqgit** [comment]
不客气
