### ISSUE TITLE
swig的模板run中prerender参数应该和nunjucks保持一致

### ISSUE THREAD

**Issue by jguang** [75team/thinkjs#500]
## DESC
swig的模板run中prerender参数

```
async run(templateFile, tVar, config){

    let options = this.parseConfig({
      autoescape: true
    }, config);
    let swig = await think.npm('swig');

    swig.setDefaults(options);
    this.prerender(config, swig);

    let tpl = swig.compileFile(templateFile);
    return tpl(tVar);
  }
```

`this.prerender(config, swig);` 应该为`this.prerender(options, swig);` 这样就和文档https://thinkjs.org/zh-cn/doc/2.2/view.html 描述的一致了，把prerender放到adapter配置中；
当然现在可以直接放到view.js的配置中；

**Comment by welefen** [comment]
多谢反馈，可以帮忙修改下代码然后发个 pull request

**Comment by welefen** [comment]
Fix by https://github.com/75team/thinkjs/commit/b262ef345843465aac02c4541f9fae30b7c97a36
