### ISSUE TITLE
关于API Token验证，请问 是都放在每个controller 的__before中吗？

### ISSUE THREAD

**Issue by dingyiming** [75team/thinkjs#501]
## DESC

- 关于API Token验证，请问 是都放在每个controller 的__before中吗？放到 base controller担心，有些方法不需要登录怎么办？怎么分开？
- 能否，验证同时拿到 用户 ID， 传递到后面具体方法中继续使用？
- API Token 是通过 查询 redis 中是否存在 token: userId 键值对，来判断为哪个用户吗？
- 然后我需要刷新 Token 时间的话，是否应该重新生成Token存储 键值对，还是说只需要改下Token时效？

## ENV

Platform: windows

Node.js Version: v6.9.1 

ThinkJS Version: 2.2.x

**Comment by geminiblue** [comment]
我这么处理了
` async __before()
   {
     let tokenConfig = await think.config("tokenneed");
     let noTokenList = tokenConfig["notoken"];
     if(!think.utils.has(noTokenList,this.getUri())){
       let token = this.http.header("token");
       if(!token)
       {
         this.error("TOKEN_VALID");
       }
       //
     }
   }
   getUri(){
     return [
       this.http.module,
       this.http.controller,
       this.http.action]
       .join("/");
   }`
然后在config里面做了个配置，不需要验证就写在配置里面
