### ISSUE TITLE
我能取到  request.protocol 是 http 还是 https 吗

### ISSUE THREAD

**Issue by hisland** [75team/thinkjs#504]
## DESC

我能取到  request.protocol 是 http 还是 https 吗? 就像 koa 里面那样

## ENV

Platform: mac

Node.js Version: v6.9.1

ThinkJS Version: v2.2.13

**Comment by welefen** [comment]
如果是用 nginx 做了反向代理，那默认情况下是取不到的，因为 nginx 到 node 始终是 HTTP 的。
有一种方式是通过一个特定的 header 字段来处理，nginx 做反向代理的时候加上这个字段，node 里获取就可以了。

**Comment by hisland** [comment]
@welefen tks, 

如你所说, 我确实是通过 nginx 反向代理过来的取不到, 不过我直接访问好像也取不到(只测了 http ), 

nginx 配置里面加 header 也考虑过, 只是看到 koa 源码里面这段代码
```
  get protocol() {
    var proxy = this.app.proxy;
    if (this.socket.encrypted) return 'https';
    if (!proxy) return 'http';
    var proto = this.get('X-Forwarded-Proto') || 'http';
    return proto.split(/\s*,\s*/)[0];
  },
```
讶异于要使用这种技巧, 也许是程序内部检测 http/https 不常需要, 故提此问.
谢谢解答, 有变通的方式处理就好办😄

**Comment by welefen** [comment]
Koa 里通过 `X-Forwarded-Proto` 来判断，那也是要在 nginx 里设置这个头信息才有效。

**Comment by welefen** [comment]
```
 location = /index.js {
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://127.0.0.1:$node_port$request_uri;
        proxy_redirect off;
    }
```

加 ` proxy_set_header X-Forwarded-Proto https` 然后在 Node.js 里就可以拿到这个 header 值，然后就可以判断了。

**Comment by hisland** [comment]
@welefen 谢谢,已经使用此种方式处理!😄

**Comment by dodoT2** [comment]
官网又上不去了 @welefen

**Comment by welefen** [comment]
@dodoT2 看了下没问题啊，你 ping 下呢？

**Comment by hisland** [comment]
我也能打开,怎么跑这来聊天了
