### ISSUE TITLE
css引用字体，报CORS错误

### ISSUE THREAD

**Issue by ymma** [75team/thinkjs#510]
## DESC

在www/static下有css文件，文件内引用了想对路径的字体。
在别的网站引用该css文件，报

has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by welefen** [comment]
需要在 nginx 上设置 CORS 头信息

**Comment by ymma** [comment]
嗯，这个我知道，但是如果是开发的时候，没有用到nginx，这个有解决方法吗

**Comment by welefen** [comment]
通过在 `common/config/config.js` 里配置来开启：

```js
resource_cors: true
```
