### ISSUE TITLE
官网打不开啦！

### ISSUE THREAD

**Issue by zhaoyao91** [75team/thinkjs#514]
官网打不开啦！翻不翻墙都不行。
https://thinkjs.org/

**Comment by welefen** [comment]
机器受到攻击，正在处理

**Comment by dingyiming** [comment]
![image](https://cloud.githubusercontent.com/assets/12537013/20653760/38aff92e-b54d-11e6-8ee0-e9279a1c1ebb.png)

**Comment by XGHeaven** [comment]
现在似乎已经修复了，我这里可以访问了。@zhaoyao91

**Comment by zhaoyao91** [comment]
@XGHeaven 还是打不开，你确定你用的不是缓存？

**Comment by XGHeaven** [comment]
我走的是http 1.1没走HTTPS

I am not shine <notifications@github.com>于2016年11月29日周二 00:12写道：

**Comment by welefen** [comment]
现在试下呢

**Comment by zhaoyao91** [comment]
可以了。
