### ISSUE TITLE
能否部署多个域名，并且不同的域名指向不同的模块

### ISSUE THREAD

**Issue by WuHuaJi0** [75team/thinkjs#515]
## DESC
这个需求不知道是不是有点奇葩。
问题是这样：用thinkjs做的一个站，但是需要绑定a.com b.com两个域名，其中我想把a.com对应整个网站，而b.com只对应其中的某个模块。

有点类似于文档里说的：子域名部署，只是这里不是子域名而是另一个域名。

好像nginx能做这样的分发，不知道在thinkjs层面能做这样的事情吗？

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
可以通过 nginx 来处理这个问题，类似于：

location = /index.js {
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://127.0.0.1:$node_port/www$request_uri;
        proxy_redirect off;
    }

在 `proxy_pass` 地址中加上对应的串（这里用 /www 举例）用于 ThinkJS 里的解析就可以了。

**Comment by WuHuaJi0** [comment]
好的，多谢：）
