### ISSUE TITLE
请求第一个参数为空时无法获取后续参数值

### ISSUE THREAD

**Issue by shrek82** [75team/thinkjs#519]
## DESC
当请求URL格式为以下格式时，无法获取参数，例如
```
http://localhost?&code=abc
```

**Comment by welefen** [comment]
参数解析直接使用 `querystring` 模块，现在不支持这种方式，所以项目里还是避免出现这种情况吧。

**Comment by shrek82** [comment]
目前使用微信公众号授权，微信初次返回code时候，是这种格式，没办法。

**Comment by welefen** [comment]
OK，我们看下如何修复下

**Comment by welefen** [comment]
Fixed by https://github.com/75team/thinkjs/commit/0a7216767755b033363022f8af6dc62bad54f3d9
