### ISSUE TITLE
【讨论】babel编译配置采用.babelrc是否合理

### ISSUE THREAD

**Issue by snadn** [75team/thinkjs#521]
项目里面，有时候babel的编译不止一套。比如有的项目里面还存在使用react写的代码需要babel处理。

此时多个babel处理的配置是不一样的。（记得之前自己使用.babel实践的时候是踩过坑的，不过后来项目里配置的处理方式有过多次变化，现在还有没有问题就不清楚了。在项目升级到最新的thinkjs后，我会关注一下这个问题。）

所以使用.babelrc对这个场景是否有影响，会不会踩坑呢？

**Comment by welefen** [comment]
不放在 .babelrc 里也会有问题，如果项目里已经有了 .babelrc 的话。
不过真要出现这种问题的话，手工修改下 package.json 的编译参数就可以了。

**Comment by snadn** [comment]
是的，所以我现在的项目是避免使用.babelrc的。然后你的意思是旧有的没有.babelrc的项目更新到最新的thinkjs也是能正常使用的，对吧？

**Comment by welefen** [comment]
@snadn  可以的，因为编译参数之前是写在 package.json 里的

**Comment by snadn** [comment]
这两天稍微看了一下，

1. 变动只是加了.bablerc文件，实现并没有变动，依托的是babel相关的机制。
2. 使用babel，只要有.bablerc，其配置就会添加到编译的配置里面，但可以使用 `bablerc: false` 选项关闭。

所以这个变动的影响其实并没什么。
