### ISSUE TITLE
提个建议：关于HTTP状态码

### ISSUE THREAD

**Issue by cos800** [75team/thinkjs#522]
## DESC
我按照`ThinkJS`文档中的写法，在controller中抛出404错误，
```js
return think.statusAction(404, this.http);
```
但是我在浏览器中查看响应的状态码却仍然是`200`

## ENV

Platform: MacOS

Node.js Version: v6.3.1

ThinkJS Version: v2.2.13

**Comment by welefen** [comment]
考虑到国内非 200 的状态码可能会被浏览器拦截，所以默认下并不会输出状态码。
需要的话在 statusAction 之前自己调用下就可以了 `http.status(404)`
