### ISSUE TITLE
如何为服务器和本地环境设置不同的缓存配置？

### ISSUE THREAD

**Issue by cos800** [75team/thinkjs#523]
## DESC
请问线上和开发环境，如何设置不同的缓存配置，
线上环境我想设置为`redis`，
但是本机我只需要用`file`作缓存。

只知道应该是修改 `/src/common/config/env/development.js` 和 `/src/common/config/env/production.js`
但格式怎么写呢？

我目前的缓存配置是写在`/src/common/config/cache.js`

## ENV

Platform: MacOS

Node.js Version: v6.3.1

ThinkJS Version: v2.2.13

**Comment by welefen** [comment]
在 `development.js` 和 `production.js` 里嵌套一层就可以了，如：

```js
export default {
    cache: {
        type: 'file',
        ...
    }
}
```

**Comment by cos800** [comment]
原来如此，看了一下文档，还确实有写到，只是不那么明显。
https://thinkjs.org/zh-cn/doc/2.2/config.html#toc-361
感激不尽啊~
