### ISSUE TITLE
如果想使用Sequelize，在哪里扩展比较方便呢

### ISSUE THREAD

**Issue by jnotnull** [75team/thinkjs#528]
## DESC

如果想使用Sequelize，在哪里扩展改动最小呢，比如还想使用model目录下的model

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
model 里不继承系统的 think.model.base，而是调用 Sequelize 的就可以了。

**Comment by jnotnull** [comment]
恩 已经弄好了 https://github.com/jnotnull/thinkjs-Sequelize

**Comment by welefen** [comment]
赞，写个介绍文章吧，我放在官方文档里。

**Comment by jnotnull** [comment]
文档已经更新了：https://github.com/jnotnull/thinkjs-Sequelize/blob/master/README.md。参考了你的文章http://www.welefen.com/post/use-mongoose-in-thinkjs.html
