### ISSUE TITLE
新手的一些小问题

### ISSUE THREAD

**Issue by wurichengn** [75team/thinkjs#530]
我是一个刚毕业的新人，也刚接触thinkjs不久，感觉这种开发风格十分适合我。目前用来开发了两个小项目，这里提出一些我的小问题。

1.关于Action命名
我们团队之前做项目使用的是PHP的laravel框架进行开发，对后台的请求经常需要如同user_login这样的请求来通过下划线细分避免一些问题。目前我想将项目移植到thinkjs下，但是发现好像并不支持action下划线，我现在的临时解决办法是通过函数生成路由去掉下划线，但我觉得这并非好办法，想问问是否有什么办法可以突破这个限制。最好是可以自己设置命中函数的规则，这样甚至可以去掉Action后缀或者用其他后缀来丰富方法。

2.关于插件的开发
thinkjs最吸引的我的地方在于他没有过多的自带插件，这不同于SSH、laravel这些框架在一定程度上限制了自由度。开发插件算是我在编程中的乐趣，这一切都是为了以后的开发效率更快。并且使用自己的逻辑开发的插件在出现任何问题时都不会太懵逼。不过thinkjs关于插件开发的文档并不多，希望官方可以给一点详细一些的教程。不知道可不可以实现我理想中的一行指令外加两三句配置就可以把一个框架嵌入到项目中（最好文件可以不用加入到模块文件夹中，可以如同node_module一样分离管理最好不过了）。

3.外部项目调用thinkjs
由于我们的项目和硬件有关，所以有开发专门的设备远程通信服务器程序。很庆幸的是这个服务器也是使用node.js开发的。由于希望可以和站点的服务器很好的交互，尝试过将服务器开发成service并在bootstrap中初始化，但是最终还是希望能够分离（因为维护上的问题）。所以如果我有一个隶属于thinkjs的其他项目，能不能通过什么方式很方便的调用model、config甚至是action。（打算过开发专门的交互用service︿(￣︶￣)︿）

4.关于官方文档
个人在看官方文档的时候感觉还是比较习惯，不过同事在一同学习thinkjs的时候反复的向我吐槽的一点就是找不到比较完整的实例教程（传说中的手把手教学），当然，其实我觉得对于现在这个更新换代这么快的时代实例教程已经很难跟上更新的速度了。

======下面的都是一些闲话了

在使用thinkjs之前我并不知道是由奇虎360旗下的团队开发的，一开始以为是thinkPHP团队的新项目，看到介绍里面"奇舞团"的时候首先联想到的就是劲舞团，紧接着就是杀马特们在我脑海闪过。当我使用一段时间之后惊喜的发现这简直就是我梦寐以求的后台开发模式，这种简单、自由、高效的框架开发者一定不简单。当我发现奇虎360的字样后更加兴奋。虽然不算是粉丝但算半个360爱好者了，浏览器、搜索引擎已经手机（最便宜的f4）都是使用的360。曾经希望进入360工作，只可惜苦于没有看到360前端工程师岗位。现在能遇到这么合适我的框架十分感激，这里也祝愿thinkjs越来越好吧！

**Comment by welefen** [comment]
user_login 的问题参加  https://thinkjs.org/zh-cn/doc/2.2/route.html#toc-bed

**Comment by wurichengn** [comment]
十分感谢，刚才测试了一下，这个问题解决了。之前没注意到这里
