### ISSUE TITLE
请问如何模糊批量删除redis缓存

### ISSUE THREAD

**Issue by jinmarcus** [75team/thinkjs#534]
似乎无法模糊批量删除redis
如果我有以下redis缓存的键值：
key1
key2
key3
我现在想批量删除，
比如：this.cache("key*", null)

似乎不起作用
只能通过

this.cache("key1", null)
this.cache("key2", null)
this.cache("key3", null)
来删除，可否增加批量删除的功能

**Comment by welefen** [comment]
不支持

**Comment by jinmarcus** [comment]
可否在下一个版本中实现，或者暴露一下radis的接口？
