### ISSUE TITLE
动态的链接数据库 dynamic link database

### ISSUE THREAD

**Issue by Messilimeng** [75team/thinkjs#540]
## DESC
   
          我想动态的链接数据库 , 数据库的配置是从数据库表中读取出来的,
          然后再去链接不同的数据库  
         I want a dynamic link database, the database configuration is read from the database table,
      And then go to a different database
@welefen 
## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
取出来后，实例化模型的时候把配置传进去就可以了，配置格式参见 db.js
