### ISSUE TITLE
使用 PM2 启动路径识别错误

### ISSUE THREAD

**Issue by alphatr** [75team/thinkjs#547]
## 如题，使用 PM2 启动，使用 think.getPath() 方法获取的路径错误

具体信息如下：

使用 PM2 启动，命令行执行 `/usr/local/bin/node /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js`

`getPath` 方法中获取的 `process.argv[1]` 为 `/usr/local/lib/node_modules/pm2/lib/ProcessContainer.js`，所以获取的路径为

```
{
  APP_PATH: '/usr/local/lib/node_modules/pm2/app',
  RESOURCE_PATH: '/usr/local/lib/node_modules/pm2/lib',
  ROOT_PATH: '/usr/local/lib/node_modules/pm2',
  RUNTIME_PATH: '/usr/local/lib/node_modules/pm2/runtime'
}
```

## ENV

Platform: linux

Node.js Version: 6.9.1

ThinkJS Version: 2.2.15

PM2 Version: 1.1.3

**Comment by welefen** [comment]
不要用这种方式。
创建项目时会创建 pm2.json 文件，执行 pm2 start pm2.json 启动
