### ISSUE TITLE
静态文件访问问题

### ISSUE THREAD

**Issue by WuHuaJi0** [75team/thinkjs#550]
是我通过nginx来部署，并按照文档里说的：src/common/config/env/prodution.js 里关闭了静态资源处理；

然后发现：访问不到静态文件!

但此时如果通过npm start来启用自带服务器的话，能访问到，因为在src/common/config/config.js中的配置是：
>export default {
  resource_on: true, //是否开启静态资源解析功能
  resource_reg: /^(static\/|[^\/]+\.(?!js|html)\w+$)/, //判断为静态资源请求的正则
}
PS：项目生成时是没有这个配置的，这里是我手动在文件里加上的，但是文档中说默认就是这样，不知道是不是文档写错了：https://thinkjs.org/zh-cn/doc/2.2/resource.html

线上访问不到静态文件，于是开始调试nginx.conf，发现：
>if ( !-f $request_filename ){
        return 200 'hello';
}
如果我把默认的这一小段配置，直接返回一个字符串的话，当我访问静态文件时：http://domain.com/static/css/main.js ，能得到字符串hello，也就是说默认的配置中，静态文件匹配到了这一小段，然后被转给index.js，所以请求不了，得到的是我自定义的404错误了。

不知道这是为何？

**Comment by WuHuaJi0** [comment]
我在https://github.com/75team/thinkjs/issues/206 看到：
>if ( !-f $request_filename ){
    rewrite (.*) /index.js;
}
如果找不到请求的文件就转给index.js，所以这里的问题似乎是：为什么会找不到这个静态文件，不知道是否可以这么理解？

**Comment by WuHuaJi0** [comment]
补充：如果引用的路径是：https://domain.com/www/static/css/main.css 的话，是能够请求到静态文件的，但是文档中给出的引用路径是：<link href="/static/css/foo.css" rel="stylesheet" />（https://thinkjs.org/zh-cn/doc/2.2/resource.html） 也就是没有包含www这个文件夹，把路径补全即可访问。

这里是否可以这里理解：如果用nginx来部署，需要把路径补全www这个文件夹路径？

**Comment by gogomarine** [comment]
Nginx的静态文件访问跟thinkjs无关。可以了解Nginx的 root 以及 alias 关键词的用法。

**Comment by WuHuaJi0** [comment]
@gogomarine 我这里的问题不只是静态文件访问，还有对thinkjs的理解问题

**Comment by welefen** [comment]
贴下你 Nginx 配置，应该是你的 root 配置问题。

**Comment by WuHuaJi0** [comment]
我这里明白了，是我的root配置有问题，我的root配置的目录只写到了代码所在目录，没有把里面的www目录加进去，所以通过nginx来访问静态文件时，静态文件需要补全www这个路径。

多谢：）

**Comment by liuhuanhui** [comment]
部署到二级目录静态怎么配置呢
