### ISSUE TITLE
error: unknown option `--es'

### ISSUE THREAD

**Issue by i5ting** [75team/thinkjs#552]
## DESC

➜  nodewebframework npm install -g thinkjs
/Users/sang/.nvm/versions/node/v7.2.1/bin/thinkjs -> /Users/sang/.nvm/versions/node/v7.2.1/lib/node_modules/thinkjs/bin/index.js
/Users/sang/.nvm/versions/node/v7.2.1/lib
└─┬ thinkjs@2.2.15 
  ├─┬ babel-runtime@6.6.1 
  │ └── core-js@2.4.1 
  ├── bluebird@3.3.5 
  ├── co@4.6.0 
  ├── colors@1.1.2 
  ├─┬ commander@2.9.0 
  │ └── graceful-readlink@1.0.1 
  ├── ejs@2.4.1 
  ├── mime@1.3.4 
  ├─┬ multiparty@4.1.2 
  │ └─┬ fd-slicer@1.0.1 
  │   └── pend@1.2.0 
  ├─┬ mysql@2.11.1 
  │ ├── bignumber.js@2.3.0 
  │ ├─┬ readable-stream@1.1.14 
  │ │ ├── core-util-is@1.0.2 
  │ │ ├── inherits@2.0.3 
  │ │ ├── isarray@0.0.1 
  │ │ └── string_decoder@0.10.31 
  │ └── sqlstring@2.0.1 
  ├── thinkit@4.9.0 
  └── validator@4.2.0 

➜  nodewebframework thinkjs new demo --es

  error: unknown option `--es'

## ENV

Platform: Mac

Node.js Version:  v7.2.1

ThinkJS Version:  thinkjs@2.2.15

**Comment by i5ting** [comment]
```
thinkjs --help

  Usage: thinkjs [command] <options ...>


  Commands:

    new <projectPath>            create project
    module <moduleName>          add module
    controller <controllerName>  add controller
    service <serviceName>        add service
    model <modelName>            add model
    middleware <middlewareName>  add middleware
    adapter <adapterName>        add adapter
    plugin <pluginPath>          create ThinkJS plugin

  Options:

    -h, --help         output usage information
    -v, --version      output the version number
    -V                 output the version number
    --es5              use es5 for project, used in `new` command
    -t, --ts           use TypeScript for project, used in `new` command
    -T, --test         add test dirs when create project, used in `new` command
    -r, --rest         create rest controller, used in `controller` command
    -M, --mongo        create mongo model, used in `model` command
    -R, --relation     create relation model, used in `model` command
    -m, --mode <mode>  project mode type(normal, module), default is module, used in `new` command
```

**Comment by ZQun** [comment]
Qun-2:thinkjs Qun$ node -v
v4.1.1
Qun-2:thinkjs Qun$ thinkjs -v

 v2.2.15

 _______ _     _       _        _  _____ 
|__   __| |   (_)     | |      | |/ ____|
   | |  | |__  _ _ __ | | __   | | (___  
   | |  | '_ \| | '_ \| |/ /   | |\___ \ 
   | |  | | | | | | | |   < |__| |____) |
   |_|  |_| |_|_|_| |_|_|\_\____/|_____/ 
                                         
Qun-2:thinkjs Qun$ thinkjs new helloworld --es

  error: unknown option `--es'


确实有问题呢～

**Comment by ZQun** [comment]
@i5ting 
https://thinkjs.org/zh-cn/doc/2.2/create_project.html
注： 从 2.2.12 版本开始，创建的项目默认为 ES6 模式，不再需要加 --es 参数, 如果想创建一个 ES5 模式项目，需要加参数 --es5。

**Comment by Messilimeng** [comment]
@i5ting  希望狼叔可以给thinkjs 做点贡献哈。

**Comment by i5ting** [comment]
在README.md文档有点小问题，哈哈

**Comment by i5ting** [comment]
@Messilimeng https://cnodejs.org/topic/5882bdc8171f3bc843f600c1  写了篇文章

**Comment by welefen** [comment]
多谢，欢迎给 ThinkJS 多提建议
