### ISSUE TITLE
babel-preset-es2015-loose is deprecated

### ISSUE THREAD

**Issue by melkir** [75team/thinkjs#557]
## DESC
As stated in the officiel repo https://github.com/bkonkle/babel-preset-es2015-loose

> The preset that this project is based on, babel-preset-es2015, now supports setting the "loose" option directly. After updating to babel-preset-es2015 v6.13.0 or higher, you can remove 'es2015-loose' from your list of presets and instead use the 'es2015 preset this way:
> 
> { presets: [ ["es2015", {"loose": true}] ] }

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
Thx, it's changed
